### ISSUE TITLE
录制视频和推流

### ISSUE THREAD

**Issue by JakeRed** [ksvc/KSYStreamer_Android#107]
我猜想你们录制和推流有一种联系，录制多次之后会影响推流。在demo上测试有这情况。

**Comment by sujia** [comment]
@JakeRed 请提供更具体的信息，多次录制后什么现象？也请提供下发生错误前后的Log, 以帮助定位问题，谢谢！

**Comment by chriszeng87** [comment]
请用最新版本试试
