### ISSUE TITLE
Streamer.toggleTorch(true); not work

### ISSUE THREAD

**Issue by ngochuu90** [ksvc/KSYStreamer_Android#109]

**Comment by zanxiaofei** [comment]
确认一下该接口返回的是true还是false，如果返回了false说明设备不支持，一般在后置摄像头的时候会支持，你可以看一下http://ksvc.github.io/KSYStreamer_Android/docs/reference/com/ksyun/media/streamer/kit/KSYStreamer.html#toggleTorch(boolean)这个接口说明
