### ISSUE TITLE
你好，我在推流的时候总是遇到一个问题Connection timed out

### ISSUE THREAD

**Issue by setsailz** [ksvc/KSYStreamer_Android#11]
每次streamer初始化KSYVIDEO_INIT_DONE成功后，就会先报1个或2个Connection timed out的错误，然后大概在初始化成功5-10秒后才真正KSYVIDEO_OPEN_STREAM_SUCC。这是为什么呢？

可能是我测试网络不太好，先关闭了吧

**Comment by chriszeng87** [comment]
请提供一下更详细的信息
