### ISSUE TITLE
你好，人脸识别是否可以自己添加，

### ISSUE THREAD

**Issue by sunqimin09** [ksvc/KSYStreamer_Android#110]
比如自己添加人脸识别，，如果可以，请问在哪里添加、
知道的 小伙伴 麻烦说一句

**Comment by chriszeng87** [comment]
可以参考这个动态贴纸的工程 https://github.com/ksvc/KSYDiversityLive_Android/tree/master/KSYStickerAndroid

这个类是具体的实现: https://github.com/ksvc/KSYDiversityLive_Android/blob/master/KSYStickerAndroid/app/src/main/java/com/ksyun/media/diversity/sticker/demo/ImgStickerProcessor.java
