### ISSUE TITLE
关于录制

### ISSUE THREAD

**Issue by JakeRed** [ksvc/KSYStreamer_Android#114]
我遇到一个问题，就是stop视频的时候，有的时候会使推流声音停一下，请问一下这块你们是否做了音频释放啥的。谢谢！

**Comment by sujia** [comment]
@JakeRed 使用FilePublisher进行录制的时候，调用stopRecord接口，如果此时正在推流，不会停止audio ；如果没有推流的任务，才会停止audio

**Comment by LoginGit** [comment]
这里我要使用音频数据回调，那是不是有可能就没audio数据，那样的话的做声音相关的问题是不是就做不了了？

**Comment by sujia** [comment]
@LoginGit 我这边不是很清楚你们的需求，我们管理各个模块的类KSYStreamer是开源的，如果有特殊需求，比如停止录制的时候不关闭音频采集，你可以自行修改
