### ISSUE TITLE
demo存在内存泄漏

### ISSUE THREAD

**Issue by shichaofei** [ksvc/KSYStreamer_Android#117]
androidstudio运行时检查发现demo存在内存泄漏，指向com.ksyun.media.streamer.logstats.StatsLogReport

**Comment by zanxiaofei** [comment]
StatsLogReport这个类是单例，进程退出时才会销毁。
不过当前版本我们SDK确实有泄漏会导致推流窗口可能没有正常退出，这个问题我们已经解决了，预计本周对外发布

**Comment by chriszeng87** [comment]
最新版本已修复这个问题

**Comment by shichaofei** [comment]
是的，已经测试过了，内存泄漏以解决
