### ISSUE TITLE
一个报错

### ISSUE THREAD

**Issue by setsailz** [ksvc/KSYStreamer_Android#12]
Fatal Exception: java.lang.IllegalStateException

android.media.MediaCodec.getBuffers (MediaCodec.java)
android.media.MediaCodec.getOutputBuffers (MediaCodec.java:551)
com.ksy.recordlib.service.hardware.a.a (Unknown Source)
com.ksy.recordlib.service.hardware.m.run (Unknown Source)
java.lang.Thread.run (Thread.java:841)

感觉是用户的手机存储空间不够引发的？

**Comment by setsailz** [comment]
还有一个类似的报错：
Fatal Exception: java.lang.IllegalStateException
android.media.MediaCodec.releaseOutputBuffer (MediaCodec.java)
com.ksy.recordlib.service.hardware.h.a (Unknown Source)
com.ksy.recordlib.service.hardware.a.a (Unknown Source)
com.ksy.recordlib.service.hardware.m.run (Unknown Source)
java.lang.Thread.run (Thread.java:841)

**Comment by chriszeng87** [comment]
已修复
