### ISSUE TITLE
Security alert: unsafe implementation of HostnameVerifier

### ISSUE THREAD

**Issue by vovkab** [ksvc/KSYStreamer_Android#121]
Google play console complains about unsafe implementation of HostnameVerifier.
Please see attached screenshot for more details:
<img width="501" alt="screen shot 2017-02-03 at 11 13 59 am" src="https://cloud.githubusercontent.com/assets/179741/22605266/f71640ea-ea03-11e6-913f-454afbc488f6.png">

**Comment by sujia** [comment]
@vovkab 这个问题将在下一版本修复，谢谢

**Comment by chriszeng87** [comment]
已修复，谢谢
