### ISSUE TITLE
直播到一个半小时以后就要报ANR异常，卡着不动，然后一阵子以后就黑屏退出了，必现的，版本是4.1.1.美颜效果开到了最高值，请问这个是什么原因，可能帮忙处理下吗谢谢

### ISSUE THREAD

**Issue by shen375650791** [ksvc/KSYStreamer_Android#122]

**Comment by zanxiaofei** [comment]
能提供一个log嘛？具体机型是？

**Comment by shen375650791** [comment]
我也没有监听到log，我们是每个机型都必现，我等下测试一下demo，就是测试一下比较麻烦，我要等一个半小时以上，昨天我们测试的工作人员是测试到95分钟的时候，必现的测试了三次，测试机型分别是小米5  oppo R9

**Comment by zanxiaofei** [comment]
是软编还是硬编，美颜使用的是哪种美颜，我们这边也同步确认一下

**Comment by shen375650791** [comment]
软编  美颜就是美白，磨皮，红润调到最高了 filter.setGrindRatio(1.0f);   filter.setWhitenRatio(1.0f);   filter.setRuddyRatio(1.0f);

**Comment by shen375650791** [comment]
你们那边确认了告诉我一下嘛，谢谢， 我也在测试的

**Comment by zanxiaofei** [comment]
好的，这边有结果会及时回复

**Comment by shen375650791** [comment]
我可以发图片给你吗。，我刚刚测试重现了有日志截图

**Comment by zanxiaofei** [comment]
直接给我发日志的log吧，发到邮箱里面就可以zanxiaofei@kingsoft.com

**Comment by zanxiaofei** [comment]
是用Demo再现的对嘛？

**Comment by shen375650791** [comment]
没有log我只有张截图，没有用demo重现，我是用的我们的软件，我马上测试demo
，昨天只是测试人员重现了我还没有测试，我马上测试demo

**Comment by overflyforever** [comment]
请问下推流的分辨率 帧率 码率具体设置是？

**Comment by zanxiaofei** [comment]
那把图片先发到我邮箱吧

**Comment by shen375650791** [comment]
发了，你收到了吗，我马上查一下哈。

**Comment by zanxiaofei** [comment]
你申请加入574179720这个群，然后在群里面发一下你的图片

**Comment by shen375650791** [comment]
预览分辨率和推流分辨率都是StreamerConstants.VIDEO_RESOLUTION_720P，推流帧率和视频码率都是15，图片在群里发了也简单介绍了情况

**Comment by shen375650791** [comment]
你好，你们调试有结果了吗，我截图上面的日志是金山推流sdk打印的吗，如果是那在什么情况下会出现那个异常，如果是我配置方面有问题我这边也可以调的

**Comment by zanxiaofei** [comment]
目前还没有再现，你发的日志并不是金山推流sdk打印的
@overflyforever

**Comment by zanxiaofei** [comment]
@shen375650791 具体你们用的哪个美颜

**Comment by zanxiaofei** [comment]
@shen375650791 你自己的app要是可以复线，最好看一下trace文件，就能知道anr发生在哪了

**Comment by shen375650791** [comment]
您好可以告诉我一下那个文件怎么获取到吗。，之前没有用过那个文件

**Comment by shen375650791** [comment]
就是trace文件

**Comment by zanxiaofei** [comment]
这个文件一般就是在发生anr的时候anroid系统自动生成的，一般在data/anr的目录下面，不同的手机可能不一样，发生anr的时候，就是系统提示你anr的时候，你看一下log，一般log里面都会有提示

**Comment by shen375650791** [comment]
嗯嗯，好的，如果没有root权限有没有其他方式可以查看到这个文件夹呀，谢谢

**Comment by zanxiaofei** [comment]
查看这个文件不需要root权限，你把它adb pull出来看就行了

**Comment by zanxiaofei** [comment]
我们这边用demo测试了几台设备都没有再现

**Comment by shen375650791** [comment]
日志导出来了，你们可以帮我看一下吗，我发你邮箱里，谢谢

**Comment by shen375650791** [comment]
那个日志你可以给我分析一下我们是哪里anr了吗。我不太会看那个日志，以前没有看过我们包名是cn.soulside.master，。谢谢

**Comment by zanxiaofei** [comment]
从trace上看anr的发生不是在推流sdk里面，

阻塞主线程在libc .so ，这个是系统的

"main" prio=5 tid=1 Native
 | group="main" sCount=1 dsCount=0 obj=0x743f8fb0 self=0xf4f76500
 | sysTid=5275 nice=0 cgrp=default sched=0/0 handle=0xf7166b34
 | state=S schedstat=( 443511314 668013010 751 ) utm=32 stm=12 core=2 HZ=100
 | stack=0xff349000-0xff34b000 stackSize=8MB
 | held mutexes=
 kernel: (couldn't read /proc/self/task/5275/stack)
 native: #00 pc 00041af0  /system/lib/libc.so (__epoll_pwait+20)
 native: #01 pc 0001a30f  /system/lib/libc.so (epoll_pwait+26)
 native: #02 pc 0001a31d  /system/lib/libc.so (epoll_wait+6)
 native: #03 pc 00012cfb  /system/lib/libutils.so (android::Looper::pollInner(int)+102)
 native: #04 pc 00012f77  /system/lib/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+130)
 native: #05 pc 00081121  /system/lib/libandroid_runtime.so (android::NativeMessageQueue::pollOnce(_JNIEnv*, _jobject*, int)+22)
 native: #06 pc 729b555d  /data/dalvik-cache/arm/system@framework@boot.oat (Java_android_os_MessageQueue_nativePollOnce__JI+96)
 at android.os.MessageQueue.nativePollOnce(Native method)
 at android.os.MessageQueue.next(MessageQueue.java:323)
 at android.os.Looper.loop(Looper.java:135)
 at android.app.ActivityThread.main(ActivityThread.java:5436)
 at java.lang.reflect.Method.invoke!(Native method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:735)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)

**Comment by shen375650791** [comment]
但是如果是系统的怎么会每次到90分钟左右的时候就出现了呀，是不是直播有些地方影响到了，还是我们程序里其他地方可能有anr出现

**Comment by zanxiaofei** [comment]
这个从这个trace里面就看不出来了，我们用Demo没有复线，你们呢？

**Comment by shen375650791** [comment]
我demo没有更新到最新版，我我测试测试，昨天我截图那个日志和推流有没有什么关联呀。我就是出现了以后就一直不停的打印我截图上的日志

**Comment by zanxiaofei** [comment]
截图上的日志是系统相机挂了，不确定是什么原因，有可能是过热

**Comment by shen375650791** [comment]
那如果出现这个异常会不会就会导致anr

**Comment by zanxiaofei** [comment]
应该不会

**Comment by shen375650791** [comment]
嗯嗯，那我在测试测试，麻烦你了
