### ISSUE TITLE
录制视频多段后推流失败

### ISSUE THREAD

**Issue by LoginGit** [ksvc/KSYStreamer_Android#123]
我们是用您那边的框架做一个推流+录制的看家的应用，一般情况下都是在录制，在使用中，录制一段时间后，拉流拉不到，日志上看一直在重连，这个情况发生时间是录制视频20秒一段的视频100端左右之后，拉流拉不下来，日志我这边捕获到之后上传，我们这边在测试测试，复现这个情况，谢谢。

**Comment by LoginGit** [comment]
你们的录制和推流应该是分开了吧

**Comment by overflyforever** [comment]
录制视频20秒一段的视频100端左右之后 这个可以详细说明下么 感觉不太理解 此外  使用的硬件大概配置可以说一下么

**Comment by LoginGit** [comment]
我们使用红米手机进行视频监控，当画面中有人经过时我们进行视频录制，20秒后恢复监控状态，在使用中我们用了硬编码，出现这个情况是一下午或者一晚上，由于测试环境人走动较多，所以录制次数很多，录制一次20秒mp4视频，一下午录制了快100端20秒的视频，导致了我后期要看视频流的时候推不上去，但是日志显示连接成功。

**Comment by sujia** [comment]
@LoginGit 推流失败返回的错误码是多少？发生错误时的日志能否发出来?

**Comment by chriszeng87** [comment]
已修复，请用最新版本试试
