### ISSUE TITLE
如何兼容GPUImage**Filter

### ISSUE THREAD

**Issue by zhileichen** [ksvc/KSYStreamer_Android#124]
gpuimage的库实现了很多基础滤镜。请问怎样在项目中兼容这些GPUImage**Filter基础滤镜?

**Comment by buliaoyin** [comment]
需要参考https://github.com/ksvc/KSYStreamer_Android/wiki/Video_Filter及demo中的自定义滤镜进行移植，两者的接口都是比较相似的，可以比较容易的移植过来。

**Comment by zhileichen** [comment]
@buliaoyin 感谢回复。  单个filter移植是比较容易，但是GPUImage lib中filter较多，有一定的工作量。 所以建议考虑提供一个兼容的Filter类，类似https://github.com/lakeinchina/librestreaming/blob/65379869629943b368cc6480ac8e92eb96c56cde/sample/src/main/java/me/lake/librestreaming/sample/hardfilter/extra/GPUImageCompatibleFilter.javahttps://github.com/lakeinchina/librestreaming/blob/65379869629943b368cc6480ac8e92eb96c56cde/sample/src/main/java/me/lake/librestreaming/sample/hardfilter/extra/GPUImageCompatibleFilter.java

**Comment by buliaoyin** [comment]
感谢建议，我们后续会调研下的
