### ISSUE TITLE
Android Studio build Error

### ISSUE THREAD

**Issue by ngochuu90** [ksvc/KSYStreamer_Android#127]
Hi @ksysdkci 

I cann't build KSYStreamer_Android 4.1.2. This is error log:

`C:\Users\ngoch\Downloads\Compressed\KSYStreamer_Android-master_3\demo\src\com\ksyun\media\streamer\demo\DemoActivity.java
Error:(16, 40) error: package com.ksyun.media.streamer.encoder does not exist
Error:(17, 42) error: package com.ksyun.media.streamer.framework does not exist
Error:(18, 36) error: package com.ksyun.media.streamer.kit does not exist
C:\Users\ngoch\Downloads\Compressed\KSYStreamer_Android-master_3\demo\src\com\ksyun\media\streamer\demo\DemoAudioFilter.java
Error:(3, 45) error: package com.ksyun.media.streamer.filter.audio does not exist
Error:(4, 42) error: package com.ksyun.media.streamer.framework does not exist
Error:(5, 42) error: package com.ksyun.media.streamer.framework does not exist
Error:(14, 38) error: cannot find symbol class AudioFilterBase
Error:(15, 13) error: cannot find symbol class AudioBufFormat
Error:(25, 46) error: cannot find symbol class AudioBufFormat
Error:(25, 15) error: cannot find symbol class AudioBufFormat
Error:(37, 38) error: cannot find symbol class AudioBufFrame
Error:(37, 15) error: cannot find symbol class AudioBufFrame
C:\Users\ngoch\Downloads\Compressed\KSYStreamer_Android-master_3\demo\src\com\ksyun\media\streamer\demo\DemoFilter.java
Error:(6, 46) error: package com.ksyun.media.streamer.filter.imgtex does not exist
Error:(7, 42) error: package com.ksyun.media.streamer.util.gles does not exist
Error:(12, 33) error: cannot find symbol class ImgTexFilter
Error:(24, 23) error: cannot find symbol class GLRender
C:\Users\ngoch\Downloads\Compressed\KSYStreamer_Android-master_3\demo\src\com\ksyun\media\streamer\demo\DemoFilter2.java
Error:(6, 46) error: package com.ksyun.media.streamer.filter.imgtex does not exist
Error:(7, 42) error: package com.ksyun.media.streamer.util.gles does not exist
Error:(12, 34) error: cannot find symbol class ImgTexFilter
Error:(24, 24) error: cannot find symbol class GLRender
C:\Users\ngoch\Downloads\Compressed\KSYStreamer_Android-master_3\demo\src\com\ksyun\media\streamer\demo\DemoFilter3.java
Error:(6, 46) error: package com.ksyun.media.streamer.filter.imgtex does not exist
Error:(7, 42) error: package com.ksyun.media.streamer.util.gles does not exist
Error:(12, 34) error: cannot find symbol class ImgTexFilter
Error:(24, 24) error: cannot find symbol class GLRender
C:\Users\ngoch\Downloads\Compressed\KSYStreamer_Android-master_3\demo\src\com\ksyun\media\streamer\demo\DemoFilter4.java
Error:(6, 46) error: package com.ksyun.media.streamer.filter.imgtex does not exist
Error:(7, 42) error: package com.ksyun.media.streamer.util.gles does not exist
Error:(12, 34) error: cannot find symbol class ImgTexFilter
Error:(24, 24) error: cannot find symbol class GLRender
C:\Users\ngoch\Downloads\Compressed\KSYStreamer_Android-master_3\demo\src\com\ksyun\media\streamer\demo\RGBABufDemoFilter.java
Error:(5, 46) error: package com.ksyun.media.streamer.filter.imgtex does not exist
Error:(6, 42) error: package com.ksyun.media.streamer.util.gles does not exist
Error:(14, 40) error: cannot find symbol class RGBABufFilter
Error:(17, 30) error: cannot find symbol class GLRender
C:\Users\ngoch\Downloads\Compressed\KSYStreamer_Android-master_3\demo\src\com\ksyun\media\streamer\demo\CameraActivity.java
Error:(44, 47) error: package com.ksyun.media.streamer.capture.camera does not exist
Error:(45, 45) error: package com.ksyun.media.streamer.filter.audio does not exist
Error:(46, 45) error: package com.ksyun.media.streamer.filter.audio does not exist
Error:(47, 46) error: package com.ksyun.media.streamer.filter.imgtex does not exist
Error:(48, 46) error: package com.ksyun.media.streamer.filter.imgtex does not exist
Error:(49, 46) error: package com.ksyun.media.streamer.filter.imgtex does not exist
Error:(50, 46) error: package com.ksyun.media.streamer.filter.imgtex does not exist
Error:(51, 46) error: package com.ksyun.media.streamer.filter.imgtex does not exist
Error:(52, 46) error: package com.ksyun.media.streamer.filter.imgtex does not exist
Error:(53, 36) error: package com.ksyun.media.streamer.kit does not exist
Error:(54, 36) error: package com.ksyun.media.streamer.kit does not exist
Error:(55, 36) error: package com.ksyun.media.streamer.kit does not exist
Error:(56, 36) error: package com.ksyun.media.streamer.kit does not exist
Error:(57, 41) error: package com.ksyun.media.streamer.logstats does not exist
Error:(58, 42) error: package com.ksyun.media.streamer.util.gles does not exist
Error:(116, 13) error: cannot find symbol class KSYStreamer
Error:(644, 24) error: package KSYStreamer does not exist
Error:(706, 24) error: package KSYStreamer does not exist
Error:(813, 27) error: package StatsLogReport does not exist
Error:(821, 13) error: cannot find symbol class OnAudioRawDataListener
Error:(830, 13) error: cannot find symbol class OnPreviewFrameListener
Error:(241, 25) error: cannot find symbol class KSYStreamer
Error:(337, 49) error: cannot find symbol variable StreamerConstants
Error:(340, 79) error: package ImgTexFilterBase does not exist
Error:(356, 9) error: cannot find symbol class CameraTouchHelper
Error:(356, 51) error: cannot find symbol class CameraTouchHelper
Error:(379, 63) error: cannot find symbol class ImgFilterBase
Error:(385, 29) error: cannot find symbol variable ImgTexFilterMgt
Error:(390, 26) error: cannot find symbol class ImgTexFilter
Error:(396, 21) error: cannot find symbol class ImgBeautyToneCurveFilter
Error:(396, 62) error: cannot find symbol class ImgBeautyToneCurveFilter
Error:(398, 81) error: cannot find symbol variable raw
Error:(402, 21) error: cannot find symbol class ImgBeautyToneCurveFilter
Error:(402, 62) error: cannot find symbol class ImgBeautyToneCurveFilter
Error:(404, 81) error: cannot find symbol variable raw
Error:(408, 21) error: cannot find symbol class ImgBeautyToneCurveFilter
Error:(408, 62) error: cannot find symbol class ImgBeautyToneCurveFilter
Error:(410, 81) error: cannot find symbol variable raw
Error:(414, 22) error: cannot find symbol class ImgFilterBase
Error:(416, 27) error: cannot find symbol class ImgFilterBase
Error:(437, 55) error: cannot find symbol class ImgBeautyProFilter
Error:(458, 43) error: cannot find symbol class ImgBeautyProFilter
Error:(616, 55) error: cannot find symbol variable KSYStreamer
Error:(644, 73) error: package KSYStreamer does not exist
Error:(682, 29) error: cannot find symbol variable StreamerConstants
Error:(686, 25) error: cannot find symbol variable StreamerConstants
Error:(689, 43) error: cannot find symbol variable StreamerConstants
Error:(692, 36) error: cannot find symbol variable StreamerConstants
Error:(696, 25) error: cannot find symbol variable StreamerConstants
Error:(700, 43) error: cannot find symbol variable StreamerConstants
Error:(706, 75) error: package KSYStreamer does not exist
Error:(814, 31) error: package StatsLogReport does not exist
Error:(821, 66) error: cannot find symbol class OnAudioRawDataListener
Error:(830, 66) error: cannot find symbol class OnPreviewFrameListener
Error:(909, 34) error: cannot find symbol class AudioFilterBase
Error:(910, 29) error: cannot find symbol class AudioReverbFilter
Error:(910, 66) error: cannot find symbol class AudioReverbFilter
Error:(916, 29) error: cannot find symbol class AudioReverbFilter
Error:(916, 66) error: cannot find symbol class AudioReverbFilter
Error:(922, 70) error: cannot find symbol class AudioFilterBase
Error:(933, 49) error: cannot find symbol variable StreamerConstants
Error:(935, 21) error: cannot find symbol variable ImgTexFilterMgt
Error:(936, 21) error: cannot find symbol variable ImgTexFilterMgt
Error:(998, 49) error: package GLRender does not exist
C:\Users\ngoch\Downloads\Compressed\KSYStreamer_Android-master_3\demo\src\com\ksyun\media\streamer\demo\CameraHintView.java
Error:(13, 47) error: package com.ksyun.media.streamer.capture.camera does not exist
Error:(21, 53) error: cannot find symbol class ICameraHintView
Error:(89, 5) error: method does not override or implement a method from a supertype
Error:(100, 5) error: method does not override or implement a method from a supertype
Error:Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.`

**Comment by buliaoyin** [comment]
Fixed, sorry for missing libksylive.jar.

**Comment by ngochuu90** [comment]
Ok
