### ISSUE TITLE
android推流版本前置摄像头不能聚焦，而后置摄像头可以聚焦。

### ISSUE THREAD

**Issue by luckyjda** [ksvc/KSYStreamer_Android#130]
android项目中使用推流SDK，发现前置摄像头无法聚焦，而后置摄像头可以聚焦。用小米4手机打开系统相机前置、后置摄像头都能对焦。而直接拿金山推流Demo跑在小米4手机，同样存在前置摄像头不能聚焦，后置摄像能聚焦。希望前置摄像头也能有聚焦的功能，谢谢。

**Comment by buliaoyin** [comment]
Mi4（包括几乎所有的Android手机）上前置摄像头都是不支持对焦的（固定焦距设计），系统相机应用中，其前置摄像头也是无法对焦的，只是可以调节重点测光区域。

**Comment by luckyjda** [comment]
嗯，好的。谢谢。
