### ISSUE TITLE
请教动态水印问题

### ISSUE THREAD

**Issue by zhileichen** [ksvc/KSYStreamer_Android#131]
Hi， 有个需求需要将一个View的内容作为水印实时混合到视频中， 研究了下WaterMarkCapture.class，混淆的比较厉害，并没有看明白。  能否提供一下建议？  谢谢

**Comment by chriszeng87** [comment]
这个是什么View呢？是图片，还是视频，还是其他的什么?

**Comment by zhileichen** [comment]
是一个绘图的View

**Comment by chriszeng87** [comment]
可以把view画到bitmap上，然后参考https://github.com/ksvc/KSYDiversityLive_Android/tree/master/KSYPipStreamerAndroid

**Comment by zhileichen** [comment]
👍   感谢
