### ISSUE TITLE
推流失败

### ISSUE THREAD

**Issue by LoginGit** [ksvc/KSYStreamer_Android#132]
02-22 09:52:05.516 645-820/com.dragonfly D/streamer: Opening output file for writing at path /storage/emulated/0/Dragonfly/com.dragonfly.data/record.video//8fc1b79f-e32a-4891-8606-83939493e17a.mp4
02-22 09:52:05.519 645-820/com.dragonfly D/streamer: open /storage/emulated/0/Dragonfly/com.dragonfly.data/record.video//8fc1b79f-e32a-4891-8606-83939493e17a.mp4 success!
02-22 09:52:05.529 645-1858/com.dragonfly D/Encoder: total dropped: 1116795 total encoded: 0
02-22 09:52:05.529 645-645/com.dragonfly V/KSYSTREAM: rtmp publisher succeed
02-22 09:52:05.536 645-27022/com.dragonfly I/OMXClient: Using client-side OMX mux.
02-22 09:52:05.561 645-27022/com.dragonfly E/OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
02-22 09:52:05.578 645-1858/com.dragonfly D/Encoder: total dropped: 1116796 total encoded: 0
02-22 09:52:05.624 645-839/com.dragonfly D/Encoder: got audio header
02-22 09:52:05.625 645-820/com.dragonfly D/streamer: addAudioStream sample_rate 44100 index 0
02-22 09:52:05.625 645-645/com.dragonfly I/Encoder: Call start on invalid state
02-22 09:52:05.625 645-1858/com.dragonfly D/Encoder: total dropped: 1116797 total encoded: 0
02-22 09:52:05.667 645-819/com.dragonfly D/streamer: Opening output file for writing at path rtmp://kanjia-dev-ms.italkcs.com/251D4623-043B-4BC6-A5BA-07C0899846F1?deviceId=10020&accessToken=CFFBAC09372245268A2A9D9BBF35E99B/live
02-22 09:52:05.677 645-1858/com.dragonfly D/Encoder: total dropped: 1116798 total encoded: 0
02-22 09:52:05.728 645-1858/com.dragonfly D/Encoder: total dropped: 1116799 total encoded: 0
02-22 09:52:05.776 645-1858/com.dragonfly D/Encoder: total dropped: 1116800 total encoded: 0
02-22 09:52:05.826 645-1858/com.dragonfly D/Encoder: total dropped: 1116801 total encoded: 0
02-22 09:52:05.876 645-1858/com.dragonfly D/Encoder: total dropped: 1116802 total encoded: 0
02-22 09:52:05.926 645-1858/com.dragonfly D/Encoder: total dropped: 1116803 total encoded: 0
02-22 09:52:05.976 645-1858/com.dragonfly D/Encoder: total dropped: 1116804 total encoded: 0
02-22 09:52:06.031 645-1858/com.dragonfly D/Encoder: total dropped: 1116805 total encoded: 0
02-22 09:52:06.077 645-1858/com.dragonfly D/Encoder: total dropped: 1116806 total encoded: 0
02-22 09:52:06.088 645-819/com.dragonfly D/streamer: Connect to rtmp://kanjia-dev-ms.italkcs.com/251D4623-043B-4BC6-A5BA-07C0899846F1?deviceId=10020&accessToken=CFFBAC09372245268A2A9D9BBF35E99B/live success!
02-22 09:52:06.091 645-645/com.dragonfly I/System.out: 460011049800101
02-22 09:52:06.092 645-645/com.dragonfly I/StatsLogReport: begin dns check
02-22 09:52:06.092 645-645/com.dragonfly V/KSYSTREAM: rtmp publisher succeed
02-22 09:52:06.104 645-839/com.dragonfly D/Publisher: audio header got
02-22 09:52:06.104 645-819/com.dragonfly D/streamer: addAudioStream sample_rate 44100 index 0
02-22 09:52:06.104 645-645/com.dragonfly I/Encoder: Call start on invalid state
02-22 09:52:06.126 645-1858/com.dragonfly D/Encoder: total dropped: 1116807 total encoded: 0
02-22 09:52:06.177 645-1858/com.dragonfly D/Encoder: total dropped: 1116808 total encoded: 0
02-22 09:52:06.197 645-814/com.dragonfly I/StatsLogReport: dns check ClientIP:211.157.227.77
02-22 09:52:06.197 645-814/com.dragonfly I/StatsLogReport: dns check LocalDnsIp:211.157.131.4
02-22 09:52:06.197 645-814/com.dragonfly I/StatsLogReport: dns check result:200
02-22 09:52:06.207 645-24778/com.dragonfly D/auth: Signature = +yHbKtz3U2YZOtgTMo0tNLAZb8A=
02-22 09:52:06.208 645-24778/com.dragonfly W/System: ClassLoader referenced unknown path: /system/framework/tcmclient.jar
02-22 09:52:06.228 645-1858/com.dragonfly D/Encoder: total dropped: 1116809 total encoded: 0
02-22 09:52:06.277 645-1858/com.dragonfly D/Encoder: total dropped: 1116810 total encoded: 0
02-22 09:52:06.311 645-24778/com.dragonfly D/KSY_ANDROID_LOG: result = {"errmsg":"success","errno":0,"logcloud":0}/n
02-22 09:52:06.332 645-1858/com.dragonfly D/Encoder: total dropped: 1116811 total encoded: 0
02-22 09:52:06.375 645-1858/com.dragonfly D/Encoder: total dropped: 1116812 total encoded: 0
02-22 09:52:06.426 645-1858/com.dragonfly D/Encoder: total dropped: 1116813 total encoded: 0
02-22 09:52:06.478 645-1858/com.dragonfly D/Encoder: total dropped: 1116814 total encoded: 0
02-22 09:52:06.529 645-1858/com.dragonfly D/Encoder: total dropped: 1116815 total encoded: 0
02-22 09:52:06.582 645-1858/com.dragonfly D/Encoder: total dropped: 1116816 total encoded: 0
02-22 09:52:06.627 645-1858/com.dragonfly D/Encoder: total dropped: 1116817 total encoded: 0

**Comment by LoginGit** [comment]
推流失败，不知道是什么原因，设备放置一段时间，这一段时间里存在录视频操作，然后当点击推流的时候，出现上述日志，当出现这个日志，推流一定是失败的，但是重新开启app是一切正常，出现这个问题的原因尚不明确，但是app放置这段时间，只有金山的操作，录制视频和推流。

**Comment by LoginGit** [comment]
请问一下，这是什么问题呢？
谢谢！

**Comment by chriszeng87** [comment]
我们定位下，请等等

**Comment by LoginGit** [comment]
今天下午也遇到了drop的问题：
02-22 17:37:57.762 2139-2298/com.dragonfly D/streamer: Opening output file for writing at path /storage/emulated/0/Dragonfly/com.dragonfly.data/record.video//f2384d50-ff82-4fa6-bdf4-3a3072116cac.mp4
02-22 17:37:57.765 2139-2298/com.dragonfly D/streamer: open /storage/emulated/0/Dragonfly/com.dragonfly.data/record.video//f2384d50-ff82-4fa6-bdf4-3a3072116cac.mp4 success!
02-22 17:37:57.778 2139-2139/com.dragonfly V/KSYSTREAM: rtmp publisher succeed
02-22 17:37:57.793 2139-2301/com.dragonfly D/Publisher: drop non-key frame
02-22 17:37:57.839 2139-2301/com.dragonfly D/Publisher: drop non-key frame
02-22 17:37:57.884 2139-2301/com.dragonfly D/Publisher: drop non-key frame
02-22 17:37:57.933 2139-2301/com.dragonfly D/Publisher: drop non-key frame
02-22 17:37:57.986 2139-2301/com.dragonfly D/Publisher: drop non-key frame

刚刚提交的问题，群里说下一个版本就好了，不知道这个问题是否跟那个问题一样。

**Comment by chriszeng87** [comment]
已修复，请用最新版本试试
