### ISSUE TITLE
这sdk是免费用的么

### ISSUE THREAD

**Issue by leeib** [ksvc/KSYStreamer_Android#134]
在官网的在线客服那询问，说要线下商务开通才能试用，但我已经将demo运行起来并能推流至我们自己的服务器，后来客服又说可能只能用一段时间，然后找我要资料让商务联系我，这是在故意这么说把我引到商务那去，还是这SDK等我打包将app上架了就不能用了要收我钱了，看里面是有个统计的jar包的，所以想问清楚一下，因为我项目只需要下这个推流sdk，金山云的其它产品暂时还不需要用到的 。

**Comment by fpzeng** [comment]
统计jar包主要做SDK稳定性统计，统计字段有[OnLogEventListener回调](http://ksvc.github.io/KSYStreamer_Android/docs/reference/com/ksyun/media/streamer/kit/KSYStreamer.html#setOnLogEventListener(com.ksyun.media.streamer.logstats.StatsLogReport.OnLogEventListener))，你可以查看原样的日志。

推流、播放SDK都是免费的，可以用于APP集成和商业应用。SDK中没有开关下发，绝不会出现APP上架后不能用的情况。

**Comment by leeib** [comment]
3Q
