### ISSUE TITLE
sound seems quite noise and low

### ISSUE THREAD

**Issue by linhphan-appsters** [ksvc/KSYStreamer_Android#148]
at first I implemented the library (v4.1.3.1) into my project the sound was very noise
after searching I followed someone's suggest to set setEnableEarMirror (false) at issue# 55.
the sound quality was improved much but still a little bit noise and quite low as well.
hope to receive any help from you. 
thanks for your efforts and the awesome library as well.

**Comment by chriszeng87** [comment]
Thank you, have you tried our demo? How is the sound like?

**Comment by linhphan-appsters** [comment]
Hi Chris,
Thank you so much for your answer.
I have tried the KSY's demo. the sound wasn't good too. It's seem that sound from real people were quite good. But when I played music on another device (not background music) the sound got noise.
I share the configurations bellow please take take look. 
I changed mStreamer.setAudioChannels(1) --> mStreamer.setAudioChannels(2) sometimes sound was low than normal.

`private void initKsyStreamer(){
        mStreamer = new KSYStreamer(this);
        mStreamTimeOutCounter = new AtomicInteger();

        //audio
        mStreamer.setAudioSampleRate(48000);
        mStreamer.setAudioKBitrate(64);
        mStreamer.setAudioChannels(1);//1: mono, 2: stereo
        mStreamer.setVoiceVolume(1f);
        mStreamer.setEnableAudioMix(false);
        mStreamer.setEnableEarMirror(false);
        mStreamer.setAudioEncodeMethod(StreamerConstants.ENCODE_METHOD_HARDWARE);
        mStreamer.setMuteAudio(false);
        mStreamer.setEnableAudioPreview(false);
//        mStreamer.getAudioFilterMgt().setFilter((AudioFilterBase) null);
//        mStreamer.getAudioFilterMgt().setFilter(new DemoAudioFilter());

        //video
        mStreamer.setPreviewFps(24);
        mStreamer.setTargetFps(24);
        mStreamer.setVideoKBitrate(1000, 1000, 400);//init, max, min --- init should be 3/4 of max, min should be 1/4 of max.
//        mStreamer.setVideoKBitrate(400);
        int videoResolution = StreamerConstants.VIDEO_RESOLUTION_480P;
        mStreamer.setPreviewResolution(videoResolution);
        mStreamer.setTargetResolution(videoResolution);
        mStreamer.setVideoCodecId(AVConst.CODEC_ID_AVC);//h264
        mStreamer.setFrontCameraMirror(false);

        mStreamer.setEncodeMethod(StreamerConstants.ENCODE_METHOD_HARDWARE);
        mStreamer.setVideoEncodeScene(VideoEncodeFormat.ENCODE_PROFILE_DEFAULT);
        mStreamer.setVideoEncodeProfile(VideoEncodeFormat.ENCODE_PROFILE_BALANCE);

//        setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
//        mStreamer.setRotateDegrees(0);

        mStreamer.setDisplayPreview(mCameraPreviewView);

        mStreamer.setEnableAutoRestart(true, 3000);

        mStreamer.setOnInfoListener(mOnInfoListener);
        mStreamer.setOnErrorListener(mOnErrorListener);
        mStreamer.setOnLogEventListener(mOnLogEventListener);
//        mStreamer.setOnAudioRawDataListener(mOnAudioRawDataListener);
//        mStreamer.setOnPreviewFrameListener(mOnPreviewFrameListener);

        mStreamer.getImgTexFilterMgt().setOnErrorListener((filter, errno) -> {
            Toast.makeText(StreamingActivityGLPlus.this, "your device doesn't support this filter", Toast.LENGTH_SHORT).show();
            mStreamer.getImgTexFilterMgt().setFilter(mStreamer.getGLRender(),
                    ImgTexFilterMgt.KSY_FILTER_BEAUTY_DISABLE);
        });

        turnOnBeautyFilter();

        // add RGBA buffer filter to ImgTexFilterMgt, this would cause performance drop,
        // only valid after Android 4.4
        //RGBABufDemoFilter demoFilter = new RGBABufDemoFilter(mStreamer.getGLRender());
        //mStreamer.getImgTexFilterMgt().setExtraFilter(demoFilter);

        // touch focus and zoom support
        CameraTouchHelper cameraTouchHelper = new CameraTouchHelper();
        cameraTouchHelper.setCameraCapture(mStreamer.getCameraCapture());
        mCameraPreviewView.setOnTouchListener(cameraTouchHelper);
        // set CameraHintView to show focus rect and zoom ratio
        cameraTouchHelper.setCameraHintView(mCameraHintView);
    }`

**Comment by chriszeng87** [comment]
Are you putting the stream device and player device too close? If so, the sound played by the player device is captured by the stream device. Try to play in a separate room.

**Comment by linhphan-appsters** [comment]
the distance from the streamer device to the player device is around 7m - 10m. and they are in a same room. is it good enough?
by the way, I rechecked last week, didn't get much noise. I was wondering whether networking connection affected the sound quality.

**Comment by chriszeng87** [comment]
Hi, we have made some changes, please update our new version and try again. Looking forward to your reply.

**Comment by linhphan-appsters** [comment]
thanks, I will update.

**Comment by linhphan-appsters** [comment]
It seems the sound is good now. I'll close the issue. thank you so much.

**Comment by hoangchungk53qx1** [comment]
@linhphan-appsters Can you give me contact information. I'm having trouble with the sound. please help me
