### ISSUE TITLE
在观看直播的时候出现这个异常是因为什么呢。可以帮我分析下吗。谢谢

### ISSUE THREAD

**Issue by shen375650791** [ksvc/KSYStreamer_Android#152]
03-24 14:11:50.801: E/RongLog(12201): [ RongExceptionHandler ] uncaughtException
03-24 14:11:50.801: E/RongLog(12201): java.lang.StackOverflowError: stack size 1038KB
03-24 14:11:50.801: E/RongLog(12201): 	at com.ksyun.media.player.https.a$2$1.verify(KsyHttpConnection.java:164)
03-24 14:11:50.801: E/RongLog(12201): 	at com.ksyun.media.player.https.a$2$1.verify(KsyHttpConnection.java:173)
03-24 14:11:50.801: E/RongLog(12201): 	at com.ksyun.media.player.https.a$2$1.verify(KsyHttpConnection.java:173)
03-24 14:11:50.801: E/RongLog(12201): 	at com.ksyun.media.player.https.a$2$1.verify(KsyHttpConnection.java:173)
03-24 14:11:50.801: E/RongLog(12201): 	at com.ksyun.media.player.https.a$2$1.verify(KsyHttpConnection.java:173)
03-24 14:11:50.801: E/RongLog(12201): 	at com.ksyun.media.player.https.a$2$1.verify(KsyHttpConnection.java:173)
03-24 14:11:50.801: E/RongLog(12201): 	at com.ksyun.media.player.https.a$2$1.verify(KsyHttpConnection.java:173)
03-24 14:11:50.801: E/RongLog(12201): 	at com.ksyun.media.player.https.a$2$1.verify(KsyHttpConnection.java:173)

**Comment by chriszeng87** [comment]
最新版本已修复，请更新
