### ISSUE TITLE
录制相关的问题

### ISSUE THREAD

**Issue by LoginGit** [ksvc/KSYStreamer_Android#157]
在乘车记录仪中，当发现异常的时候触发录制视频，很可能图片比对的时候情况已经错过了，所以能否支持一下预录的功能，只需要预录3秒，或者H264下往前录制1-2个关键帧，得到主要的情况视频，这样可能会有一个固定的缓存消耗，但是如果只提前录制3秒，应该不会有太大的消耗，望采纳，谢谢！

**Comment by chriszeng87** [comment]
你可以不停地录五分钟的片段，每次都替换上一次的旧片段，如果发现异常，就不替换了
