### ISSUE TITLE
請問有可以在視頻推流中加入圖片或是gif的接口嗎？

### ISSUE THREAD

**Issue by KoChunKai** [ksvc/KSYStreamer_Android#163]
請問有可以在視頻推流中加入圖片或是gif的接口嗎？
或如何用ImgTexFilter 去達到這個功能呢？

**Comment by chriszeng87** [comment]
可以用这个 mStreamer.showWaterMarkLogo

**Comment by KoChunKai** [comment]
那如果我要更新WaterMarkLogo 要怎麼實作？
想在一個畫面中呈現多個marklogo 是否可行？
謝謝

**Comment by buliaoyin** [comment]
调用mStreamer.showWaterMarkLogo, 参数换成需要更新的内容即可更新水印；  
要画多个水印，需要参考KSYStreamer类中关于水印的实现，自行扩展。

**Comment by KoChunKai** [comment]
好的 謝謝回覆。那有辦法使用ImgTexFilter達到水印的實現嗎？

**Comment by chriszeng87** [comment]
请参考 https://github.com/ksvc/KSYStreamer_Android/wiki/WaterMark 第四部分
