### ISSUE TITLE
直播跳转到其他页面，回来黑屏

### ISSUE THREAD

**Issue by QqManong** [ksvc/KSYStreamer_Android#164]
直播跳转到其他页面，回来黑屏。应用最小化不会黑屏

**Comment by chriszeng87** [comment]
哪个版本？机型? 系统版本号?

**Comment by QqManong** [comment]
4.0   很多机型 6.0系统  我感觉是我不会设置
@Override
    protected void onResume() {
        super.onResume();
        mStreamer.onResume();
        mStreamer.startCameraPreview();
    }

@Override
    protected void onPause() {
        super.onPause();
        mStreamer.onPause();


    }
 @Override
    public void onStop() {
        super.onStop();

        mStreamer.onPause();
        mStreamer.stopCameraPreview();
    }
这么写对吗

**Comment by chriszeng87** [comment]
1. 更新下SDK的版本到最新的吧
2. onResume里不对，请参考下Demo的写法吧
