### ISSUE TITLE
ksylive.jar没有ImgTexPreview文件

### ISSUE THREAD

**Issue by zhileichen** [ksvc/KSYStreamer_Android#167]
你好，ksylive.jar并没有ImgTexPreview文件， 但是https://github.com/ksvc/KSYStreamer_Android/blob/master/src/KSYStreamer.java 中却引入ImgTexPreview类， 请问是你们打包有问题吗？  
并且jar包中的KSYStreamer代码并没有跟上面的源文件的版本对应上。  我下载了master, 4.2.1,   4.2.0,  4.1.5都没有发现ImgTexPreview。

**Comment by chriszeng87** [comment]
抱歉，是因为KSYStreamer没有跟随版本及时更新

**Comment by zhileichen** [comment]
@chriszeng87 你这句话如何理解？     是Jar包中的KSYStreamer没有更新吗?    如果这样你们多久会再release一个版本？  很需要你们的ImgTexPreview :)

**Comment by buliaoyin** [comment]
是src/KSYStreamer.java更新的版本不对(现已修正)，jar包是正常的，不会影响正常使用。  
ImgTexPreview的实现还在内测阶段，测试通过后新版本会包含这个内容。

另外，请问你们需要ImgTexPreview的场景是什么呢？

**Comment by zhileichen** [comment]
好的，了解了。 那期待新的版本, :)  
我们想利用ImgTexPreview实现多种滤镜实时预览的功能。
谢谢！

**Comment by buliaoyin** [comment]
v4.2.2版本已发布，该版本包含了ImgTexPreview的实现，还请关注。
