### ISSUE TITLE
音效问题

### ISSUE THREAD

**Issue by peerlessyu** [ksvc/KSYStreamer_Android#168]
安卓端几时开发好音效的功能，比如说（大叔、萝莉、庄严、机器人）这几种音效

**Comment by fpzeng** [comment]
正在开发中，会在近期上线。到时候通知你

**Comment by chriszeng87** [comment]
已上线，请参考https://github.com/ksvc/KSYStreamer_Android/wiki/Audio_Filter 谢谢
