### ISSUE TITLE
推流bug导致观看视频出现画面闪烁的情况

### ISSUE THREAD

**Issue by Superstroller** [ksvc/KSYStreamer_Android#169]
出现机型：小米5 plus HUAWEI NXT-AL10

**Comment by buliaoyin** [comment]
该问题我们目前测下来，是在部分机型上，用硬编推流时，切后台再回前台的时候会偶尔出现。

我们会尽快解决这个兼容性问题的，在此之前，你可以尝试：  
1. 暂时优先用软编；
2. 禁用后台重复最有一帧mStreamer.setEnableRepeatLastFrame(false)，然后在onPause里面开启纯音频推流mStreamer.setAudioOnly(true)，onResume里面再关闭mStreamer.setAudioOnly(false)，参考：https://github.com/ksvc/KSYStreamer_Android/wiki/Audio_Streamer_Only

**Comment by buliaoyin** [comment]
v4.2.2版本已发布，该版本已修复该问题，还请关注。
