### ISSUE TITLE
硬编崩溃

### ISSUE THREAD

**Issue by tangxiangpi** [ksvc/KSYStreamer_Android#17]
手机是 huawei Che2-UL00 api19
推流几秒钟就挂了
IllegalStateException:
at MediaCodec.getBuffers(Native method)
...
at com.ksy.recordlib.service.hardware.a.a
at com.ksy.recordlib.service.hardware.m.run

**Comment by chriszeng87** [comment]
请问版本号是？

**Comment by tangxiangpi** [comment]
@chriszeng87 3.3.0.0 ,3.3.0.2都有

**Comment by chriszeng87** [comment]
华为的Android系统版本号是?4.3以下不支持硬编

**Comment by gordonpro** [comment]
这个手机我看了一下是 4.4的。但是CPU 貌似是 海思麒麟620。 我之前用MTK的手机做硬解时，也有过类似底层库报错。

**Comment by setsailz** [comment]
Fatal Exception: java.lang.IllegalStateException
 Raw Text
android.media.MediaCodec.native_dequeueOutputBuffer (MediaCodec.java)
android.media.MediaCodec.dequeueOutputBuffer (MediaCodec.java:1033)
com.ksy.recordlib.service.hardware.a.a (Unknown Source)
com.ksy.recordlib.service.hardware.m.run (Unknown Source)
java.lang.Thread.run (Thread.java:831)

我也看到这个错误了。在这几款华为手机上出现较多：HUAWEI P7-L09 CHE-TL00H46 HUAWEI VNS-DL，以及魅族MX4 pro上也出现过。

**Comment by chriszeng87** [comment]
硬编不是所有机型都OK，如果你是我们的客户的话，可以找我们的商务要白名单

**Comment by setsailz** [comment]
@chriszeng87 你的意思是通过你们的白名单来区分对待，如果不支持硬解的话就使用软解？SDK里不提供检测是否支持硬解？

**Comment by chriszeng87** [comment]
是的，SDK暂时不直接提供白名单的功能，在接下来三四个版本后，会支持硬编失败后，自动切换到软编

**Comment by chriszeng87** [comment]
白名单已上线，请参考 https://github.com/ksvc/KSYStreamer_Android/wiki/device_config
