### ISSUE TITLE
Video Profile 的問題

### ISSUE THREAD

**Issue by bingdow** [ksvc/KSYStreamer_Android#175]
<img width="1011" alt="2017-05-17 5 36 12" src="https://cloud.githubusercontent.com/assets/2859025/26147886/81d75ed4-3b27-11e7-938f-a6c3f22cdd88.png">

請問該如何調用 setVideoEncodeProfile() 把 video profile 設置成 main? 或是 balance, high_performance, low, default 哪一個是最接近 main？

**Comment by bingdow** [comment]
Main Profile (MP, 77)
This profile is used for standard-definition digital TV broadcasts that use the MPEG-4 format as defined in the DVB standard.[35] It is not, however, used for high-definition television broadcasts, as the importance of this profile faded when the High Profile was developed in 2004 for that application.

High Profile (HiP, 100)
The primary profile for broadcast and disc storage applications, particularly for high-definition television applications (for example, this is the profile adopted by the Blu-ray Disc storage format and the DVB HDTV broadcast service).

**Comment by buliaoyin** [comment]
请参考：
https://github.com/ksvc/KSYStreamer_Android/wiki/liveScene

关于EncodeProfile的几个预设档次，是我们根据实际测试情况确定的，从节省CPU资源，到提高编码质量，你提到的最接近main指的应该是最节省cpu资源吧，那可以配置为ENCODE_PROFILE_LOW_POWER.

**Comment by bingdow** [comment]
@buliaoyin 試過了，設置成 ENCODE_PROFILE_LOW_POWER 分析出來 video profile 依然是 high
但 audio profile 設置成 low power 分析出來果然如文檔所說，變成 LC 了

**Comment by buliaoyin** [comment]
@bingdow 目前我们确实是不支持设置编码的profile的(baseline, main, high)，目前预设的ENCODE_PROFILE只是针对编码功耗进行优化的。

你那边需要设置profile是基于什么用途呢？

**Comment by bingdow** [comment]
@buliaoyin OK 知道了
