### ISSUE TITLE
耳返问题

### ISSUE THREAD

**Issue by mikukon** [ksvc/KSYStreamer_Android#176]
在设置耳返之后，如果添加了BGM，即使将setEnableAudioMix()为false，依然能在录制后的视频中听到bgm，只是音量比mute的时候小

**Comment by buliaoyin** [comment]
还请提供使用的SDK版本，v4.2.2版本未复现该问题。

还请留意是否耳机跟mic离得比较近？

**Comment by mikukon** [comment]
谢谢，闹出乌龙了，已解决
