### ISSUE TITLE
4.X SDK错误码 -4001 是什么原因

### ISSUE THREAD

**Issue by gordonpro** [ksvc/KSYStreamer_Android#177]
我从对照表中看到 `-4001` 是3.X 版本时有对应`KSYVIDEO_WLD_UPLOAD`。 我用的是4.X版本的SDK，请问这个错误码是代表什么错误

**Comment by chriszeng87** [comment]
你是说onError回调收到-4001的错误？这个错误一般是推流的地址有问题

**Comment by gordonpro** [comment]
是的，onError -4001
