### ISSUE TITLE
金山云录制的mp4，chrome浏览器无法播放。

### ISSUE THREAD

**Issue by zhengchengbin610** [ksvc/KSYStreamer_Android#179]
金山云的伙伴们好，现在由于项目中的一个录播设备存放的 金山云sdk 录制的mp4无法播放；
请协助支持一下；

**Comment by chriszeng87** [comment]
能把这个视频的在线地址发到这里么?

**Comment by zhengchengbin610** [comment]
谢谢，问题已经解决了，是音频编码不支持，换成LC-AAC就都兼容了。

**Comment by 978749951** [comment]
怎么设置可以弄成lc-aac？只能通过ffmpeg转吗？还是金山云的直播端，修改个参数就可以了
