### ISSUE TITLE
帧率设置无效

### ISSUE THREAD

**Issue by zhengchengbin610** [ksvc/KSYStreamer_Android#180]
软编码下，部分手机设置预览帧率和编码帧率都是30帧，录制的mp4帧却率非常低 只有7,8帧；（换成硬编码则录制文件流畅）；金山的伙伴们，请问这个有没有接口可以控制录制的文件进行，谢谢！

**Comment by buliaoyin** [comment]
软编码的cpu占用是远高于硬编码的，如果录制的分辨率比较高(720p甚至1080p)，那么受制于手机本身的性能，软编码可能只能达到你所说的7,8帧的编码速度。  
对于高分辨率高码率的视频录制，我们建议还是采用硬编码，如果需要做短视频，可以使用我们的短视频SDK进行转码，以降低码率。

**Comment by zhengchengbin610** [comment]
的确，我们就是在720P和1080P 分辨率就会出现严重丢帧，但是又没有办法知道手机性能好还是不好，但是产品定义 是需要高清视频的，所以这个问题 还是个难题。还有就是手机本身自带的录像软件是可以录制高清流畅的产品的，这个如何理解呢？我们设置又这个丢帧问题的手机用硬编码方式，虽然录制的720P流畅了，但是画质变得好差，马赛克严重。

**Comment by buliaoyin** [comment]
手机本身的相机录制是用的硬件编码，你们这种高分辨率、高帧率的需求还是建议使用硬件编码。  
至于画质差的问题，是设置的码率过低引起的，一般使用硬编码时，720p下4M的码率才能避免可见的马赛克，1080p下则甚至需要8M以上。
