### ISSUE TITLE
Not working for API 23+: libksylive.so: has text relocations

### ISSUE THREAD

**Issue by vovkab** [ksvc/KSYStreamer_Android#181]
Hello

Not working on emulator for API 23+
Tried latest version v2.3.2, and others, they are all crashes with:

```
05-26 14:28:45.582 XXX E/linker: /data/app/XXX-2/lib/x86/libksylive.so: has text relocations
05-26 14:28:45.583 XXX E/LibraryLoader: No libksylive.so! Please check
05-26 14:28:45.583 XXX E/art: No implementation found for long com.ksyun.media.streamer.filter.audio.AudioSLPlayer._init() (tried Java_com_ksyun_media_streamer_filter_audio_AudioSLPlayer__1init and Java_com_ksyun_media_streamer_filter_audio_AudioSLPlayer__1init__)
```

This is probably why it crashes:
https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#Text-Relocations-Enforced-for-API-level-23

**Comment by buliaoyin** [comment]
Thanks for your comment. The text relocations only exist in x86 library, we will fix it in the next few release.

**Comment by chriszeng87** [comment]
Fixed.
