### ISSUE TITLE
硬编码 ,画质很差

### ISSUE THREAD

**Issue by zhengchengbin610** [ksvc/KSYStreamer_Android#182]
由于部分软编码录制视频会丢帧，所以强制改成硬编码，录制视频分辨率720P，设置码率1.5Mbps，max 2048Mbps, min 1024Mbps，结果帧率达到设置帧率，但是画质很差

**Comment by buliaoyin** [comment]
硬件编码的画质，是由手机硬件本身决定的，同码率下的画质是远低于软编码的，一般720p下要达到比较好的画质，码率需要4-8Mbps，如果觉得画质差，可以提高码率，直到画质可接受为止。
