### ISSUE TITLE
请问有没有方法，可以取得音频滤镜处理后的声音资料？

### ISSUE THREAD

**Issue by falll2000** [ksvc/KSYStreamer_Android#185]
您好，感谢贵公司开发的SDK

请问贵公司开发的音频滤镜中，有没有取得变声后音频资料的方法
目前我需要取得音频资料后再在处理

谢谢

**Comment by chriszeng87** [comment]
资料？

**Comment by falll2000** [comment]
对的，我需要取得经过"声音滤镜"处理过后的"声音资料"，不晓得有没有接口或方法可以得到声音资料？

**Comment by buliaoyin** [comment]
参考这里：  
https://github.com/ksvc/KSYStreamer_Android/wiki/Audio_Filter#12-%E8%87%AA%E5%AE%9A%E4%B9%89%E9%9F%B3%E9%A2%91%E6%BB%A4%E9%95%9C

可以在变声filter后加一个自定义filter，在自定义filter内即可获取、处理变声后的音频数据。
