### ISSUE TITLE
弱网监听问题

### ISSUE THREAD

**Issue by xiangyutian** [ksvc/KSYStreamer_Android#186]
推流sdk中的弱网下状态监测是否只能靠KSYStreamer.OnInfoListener中的StreamerConstants.KSY_STREAMER_FRAME_SEND_SLOW来监测？

**Comment by buliaoyin** [comment]
监听该回调是一种方式，也可以结合推流的上行带宽来监测：  
http://ksvc.github.io/KSYStreamer_Android/docs/reference/com/ksyun/media/streamer/kit/KSYStreamer.html#getCurrentUploadKBitrate()
