### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.ksyun.media.streamer.filter.audio.AudioResample.a(int, int)' on a null object reference

### ISSUE THREAD

**Issue by StaticCoder** [ksvc/KSYStreamer_Android#187]
so和jar包都是最新的，前两天才集成的。推流客户端切换到后台再切回来有时候会报这个错，直接崩。怎么解决呢？

java.lang.RuntimeException:Unable to resume activity {package(包名).StartLiveActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.ksyun.media.streamer.filter.audio.AudioResample.a(int, int)' on a null object reference
2 android.app.ActivityThread.performResumeActivity(ActivityThread.java:3389)
3 ......
4 Caused by:
5 java.lang.NullPointerException:Attempt to invoke virtual method 'void com.ksyun.media.streamer.filter.audio.AudioResample.a(int, int)' on a null object reference
6 com.ksyun.media.streamer.filter.audio.AudioResampleFilter.setOutFormat(SourceFile:31)
7 com.ksyun.media.streamer.kit.KSYStreamer.setAudioParams(SourceFile:1613)
8 com.ksyun.media.streamer.kit.KSYStreamer.setPreviewParams(SourceFile:1631)
9 com.ksyun.media.streamer.kit.KSYStreamer.startCameraPreview(SourceFile:1534)
10 com.ksyun.media.streamer.kit.KSYStreamer.startCameraPreview(SourceFile:1513)
11 package.StartLiveActivity.onResume(SourceFile:1317)

调用代码如下：
 @Override
    public void onResume() {
        super.onResume();
        // 一般可以在onResume中开启摄像头预览
        mStreamer.startCameraPreview();
        // 调用KSYStreamer的onResume接口
        mStreamer.onResume();
  
    }

**Comment by buliaoyin** [comment]
还请提供下你那边的集成代码，以及测试机型。  
另外，你也可以以demo为基础进行测试，一步一步拿掉你不需要的功能，以定位集成的问题出在哪里。
