### ISSUE TITLE
推流SDK音频时间戳跳跃，不是单增的

### ISSUE THREAD

**Issue by mr-zt** [ksvc/KSYStreamer_Android#190]
请大牛帮忙看下音频时间戳的问题：
采样率为44kHz的音频，dts 间隔应为 23.27ms
实际音频间隔在20与47左右交替出现，而 size 的变化并没有两倍的差距，这样会导致音频出现失声的情况（rtmp 流用 vlc 会有无声，用 srs player 无该现象
![image](https://user-images.githubusercontent.com/3492551/27118353-708414aa-510d-11e7-810d-9aa776a65357.png)
而录制成 mp4后音频戳还是会有跳变的现象，也导致播放出现噪音（chrome）,无声（vlc）

**Comment by chriszeng87** [comment]
谢谢反馈，我们先确认下

**Comment by buliaoyin** [comment]
从描述来看，是采集编码过程中，有一些音频帧被丢掉了。

还请提供下你使用的推流SDK版本，用法，以及用来推流的机型。

**Comment by mr-zt** [comment]
Android 金山推流sdk2.3.0  ,用法是按照官方文档的用法，具体机型现在还不确定，不过有将近40%以上的用户都这样

**Comment by mr-zt** [comment]
对应推流sdk4.2.0

**Comment by buliaoyin** [comment]
还请再确认下，这个现象使用我们的推流demo是否可以复现？

**Comment by mr-zt** [comment]
可以复现的，用demo也是这样，手机用的是华为mate 9 测试的

**Comment by buliaoyin** [comment]
可以复现是指用v4.2.0的demo，在华为mate 9上直播推流，用vlc播放，会没有声音？

我们内部验证了多个机型，还没有发现哪个机型推的流vlc播放无声的，同时也验证了下本地录制功能录制下来的mp4文件，音频pts也是比较均匀连续的，未发现有音频帧缺失的现象。
