### ISSUE TITLE
自適應碼率問題

### ISSUE THREAD

**Issue by bingdow** [ksvc/KSYStreamer_Android#193]
根據文檔的說法

> 
> 初始码率 initVideoKbps:
> 刚启动编码时，网络状态未知，可以从较低的码率开始，让码率自适应调整到合适的值
> 最高码率 maxVideoBps:
> 码率自适应的调整上限，表示当网络状况良好时，视频编码所能达到的最大平均码率值
> 最低码率 minVideoKbps:
> 码率自适应的调整下限，可根据需求设置

所以 maxVideoBps 是「網路狀態良好下的『平均碼率』」，我目前這三個參數設置分別是 400, 500, 300
也就是最高碼率設置為 500 而音頻碼率設置為 48

從後台監看即時推流碼率發現從起始的 4xx 左右後一路上升至 600 多並穩定在 600 多，大約是 66x 這個數字就沒再降下來了，雖然明白定義上的 maxVideoBps 是平均碼率，想請教下有沒有辦法設置一個「碼率最大值」使推流碼率永遠保持在最大值以下？

**Comment by chriszeng87** [comment]
您说的对，这里的maxVideoBps只是最大平均码率。您可以去了解一下编码器相关的资料，应该是没有这种非常严格地去限制码率到某一个最大值之下的这种做法。可以通过设置ratetol参数来让码率变化基本上在最大值以下，但偶尔也会超过这个理论上的最大值，这样做有一个坏处就是图像的质量会降低。码率只是一个方面，还请综合地来看待这个问题，谢谢。

**Comment by buliaoyin** [comment]
还请确认下你使用的推流SDK版本号，你描述的现象应该在最新的v4.2.3版本修复了。
参见：https://github.com/ksvc/KSYStreamer_Android/releases/tag/v4.2.3

还请更新后再测试，更新后可能还有偶尔稍微高出设置的最高码率的问题，那就属于编码器码率控制的误差范围了。

**Comment by bingdow** [comment]
@buliaoyin 看了下發佈日誌，那麼 setBwEstStrategy() 也要一併調用嗎？

**Comment by buliaoyin** [comment]
不需要的，setBwEstStrategy只是开放了不同的码率自适应策略。

**Comment by bingdow** [comment]
@buliaoyin 好的謝謝
