### ISSUE TITLE
水印logo动态设置会变形，

### ISSUE THREAD

**Issue by shanyaodan** [ksvc/KSYStreamer_Android#197]
我先把把单行文字添加进logo,然后动态换成多行文字，就会出现拉伸的情况，第三次设置又就好了。

**Comment by shanyaodan** [comment]
设置方法 mStreamer.showWaterMarkLogo(mLogoPath, 0.1f, 0.8f, 1f, 0, 0.8f);

**Comment by buliaoyin** [comment]
感谢反馈，我们确认下。

你也可以尝试给水印设置Bitmap对象，而不是路径来试试这个问题是否还存在。

**Comment by buliaoyin** [comment]
fixed in v4.3.1
