### ISSUE TITLE
ANDROID竖屏录制，播放器看到的画面是倒的

### ISSUE THREAD

**Issue by garrickjubiao** [ksvc/KSYStreamer_Android#2]
使用ANDROID推流sdk发布直播，我在我的播放器里面看到的画面是倒的。 

这个怎么解决？

**Comment by chriszeng87** [comment]
请问是什么机型呢，使用的分辨率是？是用前置，还是后置摄像头推的？请提供更详细的信息

**Comment by tian9246** [comment]
这应该是尚未初始化完成造成的，请在KSYVIDEO_INIT_DONE（1000）之后调用startStream接口
