### ISSUE TITLE
請問原始音頻數據處理的回調參數含義？

### ISSUE THREAD

**Issue by bingdow** [ksvc/KSYStreamer_Android#202]
如題

`short[] OnAudioRawData(short[] data, int count);`

這個函式中的第二個參數 count 是什麼呢？

**Comment by buliaoyin** [comment]
这个是比较旧的版本了吧，具体可以看javadoc文档：  
http://ksvc.github.io/KSYStreamer_Android/docs/reference/com/ksyun/media/streamer/kit/OnAudioRawDataListener.html
