### ISSUE TITLE
录制功能自动触发推流

### ISSUE THREAD

**Issue by jig1234** [ksvc/KSYStreamer_Android#205]
首先，手机不支持H.265硬编，当设置为H.265硬编时，在录制过程中，会自动转变为软编，在没有人为触发推流的情况下，回调了推流成功的状态码，进行自动推流。非H.265硬编情况下，一切正常，录制不会造成自动推流。
H.265硬编情况下启动录制后日志如下：
`07-20 17:12:13.937 7263-7263 D/CameraActivity: KSY_STREAMER_CAMERA_INIT_DONE`
`07-20 17:12:13.944 7263-7263 D/CameraActivity: OnInfo: 1002 msg1: 0 msg2: 0`
`07-20 17:12:19.451 7263-7263 D/CameraActivity: KSY_STREAMER_OPEN_FILE_SUCCESS`
`07-20 17:12:19.519 7263-7263 D/CameraActivity: KSY_STREAMER_VIDEO_ENCODER_ERROR_UNSUPPORTED`
`07-20 17:12:19.520 7263-7263 E/CameraActivity: Got HW encoder error, switch to SOFTWARE mode`
`07-20 17:12:23.729 7263-7263 D/CameraActivity: KSY_STREAMER_OPEN_STREAM_SUCCESS`

最后，KSYStreamer版本为4.3.0.1，非常感谢。

**Comment by buliaoyin** [comment]
这个是demo中的错误重试逻辑有点问题，录制失败也会进行推流的重试，你在集成时，只需要区分下录制时的错误码，如果是录制错误就不要重试推流即可。

**Comment by jig1234** [comment]
已找到相关逻辑，非常感谢
