### ISSUE TITLE
请问最新版本中的syapm.so是用来处理什么的,是否必须集成的?

### ISSUE THREAD

**Issue by dandan9628** [ksvc/KSYStreamer_Android#209]

**Comment by chriszeng87** [comment]
是用来做噪声抑制的，如果不需要噪声抑制，可以不集成

**Comment by dandan9628** [comment]
谢谢，还有个疑问，最新版sdk公开的KSYStreamer.java中的AudioAPMFilterMgt类不能import到

**Comment by buliaoyin** [comment]
AudioAPMFilterMgt不能import的问题已在v4.3.3修复。
