### ISSUE TITLE
CameraActivity 權限請求 READ_EXTERNAL_STORAGE？

### ISSUE THREAD

**Issue by bingdow** [ksvc/KSYStreamer_Android#214]
範例程式碼在 CameraActivity 裡請求權限時除了相機麥克風
也請求了 READ_EXTERNAL_STORAGE
請問這是必要的嗎？

**Comment by buliaoyin** [comment]
这个是用来读取sdcard上的背景音乐、水印图、背景图的

**Comment by bingdow** [comment]
@buliaoyin 那濾鏡遮罩檔案呢？

**Comment by buliaoyin** [comment]
打包到app的assets下面就不需要了哦
