### ISSUE TITLE
有没有渲染接口呢？

### ISSUE THREAD

**Issue by a544393709** [ksvc/KSYStreamer_Android#216]

**Comment by chriszeng87** [comment]
请描述地更清楚一些，谢谢

**Comment by a544393709** [comment]
推流用的金山的  现在我们需要接入第三方  开为科技的 人脸识别  美颜功能  需要用到 视频渲染接口

**Comment by chriszeng87** [comment]
我们正在和开为科技对接，会在进期提供对接好的SDK，到时候可以集成可以非常快。不过你也可以自己尝试一下，这些都是开放的

**Comment by a544393709** [comment]
好的  非常感谢

**Comment by a544393709** [comment]
@chriszeng87  大概什么时间 能提供对接好的开为科技 SDk

**Comment by chriszeng87** [comment]
https://github.com/ksvc/KSYDiversityLive_Android/tree/master/KSYKiwiAndroid   已上线

**Comment by a544393709** [comment]
非常感谢
