### ISSUE TITLE
可否预设后摄像头?

### ISSUE THREAD

**Issue by herman602** [ksvc/KSYStreamer_Android#22]
请问如何在初始化完成后直接开启后摄像头
                case RecorderConstants.KSYVIDEO_INIT_DONE:
                	mStreamer.switchCamera();

这样子会有点卡顿
有没有直接开启后摄像头的方法?

**Comment by chriszeng87** [comment]
KSYStreamerConfig的setDefaultFront方法，设置为false就可以了

**Comment by herman602** [comment]
谢谢，已经解决。

**Comment by MrDing8008** [comment]
您好，请问是直接设置这个 setFrontCameraMirror(false)吗？    
需求：初始化完成后直接开启后置摄像头

**Comment by buliaoyin** [comment]
@MrDing8008 仔细看下工程首页的说明就清楚了哦。

![image](https://user-images.githubusercontent.com/4070520/32164501-bf2c3bfa-bd2d-11e7-80a2-cf61e6c37561.png)

**Comment by MrDing8008** [comment]
好的，已解决，谢谢！
