### ISSUE TITLE
推流分辨率问题

### ISSUE THREAD

**Issue by xiangyutian** [ksvc/KSYStreamer_Android#220]
用户反馈使用mate8手机在推流直播后，生成的视频分辨率是不同的，有720x1280，也有720x1208的，我们推测用户可能存在隐藏或者显示虚拟键后推流的情况，请问是否还会存在其他原因？

**Comment by buliaoyin** [comment]
你的推流分辨率设置的是720P吧？这种设置下，SDK会根据实际预览尺寸进行调整，比如显示虚拟按键后，尺寸就变成720x1208了。

如果想固定推流分辨率，你可以调用 mStreamer.setTargetResolution(720, 1280); 这样如果预览分辨率的比例不是9:16那么SDK会进行裁剪，并严格按照720x1280的分辨率推流。

**Comment by xiangyutian** [comment]
灰常感谢ing....
