### ISSUE TITLE
how to set app only use back camera by default.

### ISSUE THREAD

**Issue by quickstreamingmedia** [ksvc/KSYStreamer_Android#222]
how to set only use back camera instead of front one by default?

**Comment by buliaoyin** [comment]
mStreamer.setCameraFacing

http://ksvc.github.io/KSYStreamer_Android/docs/reference/com/ksyun/media/streamer/kit/KSYStreamer.html#setCameraFacing(int)

**Comment by quickstreamingmedia** [comment]
please provide appropriate code and where to implement.

**Comment by buliaoyin** [comment]
Just call `mStreamer.setCameraFacing(CameraCapture.FACING_FRONT); ` before `mStreamer.startCameraPreview();`

**Comment by quickstreamingmedia** [comment]
mStreamer.setCameraFacing(CameraCapture.FACING_BACK); worked.
