### ISSUE TITLE
cancel autofocus does not work cause the methods are deprecated.

### ISSUE THREAD

**Issue by quickstreamingmedia** [ksvc/KSYStreamer_Android#225]
![image](https://user-images.githubusercontent.com/6527923/29024017-5580c1d2-7b9a-11e7-90d1-dea967bd1686.png)

can any one specify make focus to infinite.

thanks in advance.

**Comment by buliaoyin** [comment]
Please refer to https://developer.android.com/reference/android/hardware/Camera.html and https://developer.android.com/reference/android/hardware/Camera.Parameters.html

**Comment by quickstreamingmedia** [comment]
@buliaoyin  please help me code to make focus to infinity.

**Comment by quickstreamingmedia** [comment]
expecting some update but i am unable to get it. please help me

**Comment by quickstreamingmedia** [comment]
@buliaoyin  after some research i am able to achieve focus to infinity

![image](https://user-images.githubusercontent.com/6527923/29238381-6ffec30c-7f5e-11e7-92b3-727d53a1bf04.png)
i think it will help some one who wants to do.

**Comment by quickstreamingmedia** [comment]
i thought this repo issue support is worse than the things i used in opensource world
