### ISSUE TITLE
show text as watermark 

### ISSUE THREAD

**Issue by quickstreamingmedia** [ksvc/KSYStreamer_Android#227]
hello everyone can some one can help me to show text as watermark on stream. beside timer direct code please

**Comment by quickstreamingmedia** [comment]
expecting some update but i am unable to get it. please help me

**Comment by chriszeng87** [comment]
Try this: https://github.com/ksvc/KSYStreamer_Android/wiki/View_Streaming
You can show any custom android.view.View with this method. If you can not understand Chinese, please use Google translate.
