### ISSUE TITLE
推流断网重连，RtmpPubThread 线程不断增加

### ISSUE THREAD

**Issue by shuinong** [ksvc/KSYStreamer_Android#228]
重现方法：
    1.  在CameraActivity.java文件中，mOnErrorListener回调方法内，添加断网事件回调：
![default](https://user-images.githubusercontent.com/4973439/29115701-1acb2432-7d2b-11e7-9b0c-60da32b9827e.png)

    2.  开始推流， 推流成功之后，断开WiFi网络，让程序触发回调事件(上图的那几个事件)，并重连逻辑
    3.  使用android studio 2.4预览版（低版本的看不到），查看线程状态，可以看到RtmpPubThread不断的增加. (也可以在Android  Studio的Terminal 页面中，通过adb shell进入手机，查看进程的线程数量)

        
![default](https://user-images.githubusercontent.com/4973439/29116063-405b0e78-7d2c-11e7-8acd-102d9e5d1e22.png)

    4. 当不断触发重连逻辑的时候，即可看到RtmpPubThread 线程数量不断增加.
    5. SDK版本：2.3.0

**Comment by buliaoyin** [comment]
感谢反馈，问题已定位，会在后续版本修复。

**Comment by chriszeng87** [comment]
已修复并上线，请确认 https://github.com/ksvc/KSYStreamer_Android/releases/tag/v4.3.2

**Comment by shuinong** [comment]
@chriszeng87 请问这是对应哪个版本的SDK，通过compile 'com.ksyun.media:libksylive-armv7a:2.4.1'这种方式。
v4.3.2是12天前发布的哦？而且还是有这个问题的

**Comment by chriszeng87** [comment]
是2.4.2修复的，试试compile 'com.ksyun.media:libksylive-armv7a:2.4.2'

**Comment by chriszeng87** [comment]
抱歉，这个修复已经进我们的代码库了，但是还没对外发布

**Comment by shuinong** [comment]
好的，谢谢，我试一下，等一下告诉你们 @chriszeng87

**Comment by chriszeng87** [comment]
先不用试了。。。现在线上最新的版本还没包含这个修复。。。

**Comment by shuinong** [comment]
哦，好的，谢谢 @chriszeng87

**Comment by VipMinF** [comment]
@chriszeng87 我的也出现这个问题，请问什么时候修复好

**Comment by chriszeng87** [comment]
抱歉，我们即将发布的版本会修复

**Comment by buliaoyin** [comment]
@shuinong @VipMinF 推流端v4.3.3版本已发布，该问题已修复，还请确认。

**Comment by shuinong** [comment]
感谢，已解决 @buliaoyin
