### ISSUE TITLE
希望能尽快回复一下。invalid argument经常出现这个问题

### ISSUE THREAD

**Issue by z2045217** [ksvc/KSYStreamer_Android#23]
我接入了金山云直播的推流器。按照demo里面写的。为什么上传不稳定。经常断线。还有经常返回这个invalid argument错误。断开连接。

videoBitrate = 800；
videoResolution = RecorderConstants.VIDEO_RESOLUTION_540P；
encode_method = KSYStreamerConfig.ENCODE_METHOD.SOFTWARE；
landscape = false；
isFrontCameraMirror = true；
focus_manual = false;
GLSurfaceView mCameraPreview = (GLSurfaceView)findViewById(R.id.camera_preview);
      KSYStreamerConfig.Builder builder = new KSYStreamerConfig.Builder();
//    builder.setmUrl(Live_PUSH);
      builder.setFrameRate(15);
      //设置最高码率，即目标码率
      builder.setMaxAverageVideoBitrate(videoBitrate);
      //设置最低码率
      builder.setMinAverageVideoBitrate(videoBitrate \* 2 / 8);
      //设置初始码率
      builder.setInitAverageVideoBitrate(videoBitrate \* 5 / 8);

```
  if (audioBitrate > 0) {
     builder.setAudioBitrate(audioBitrate);
  }

  builder.setVideoResolution(videoResolution);

  builder.setEncodeMethod(encode_method);

  builder.setSampleAudioRateInHz(44100);
  builder.setEnableStreamStatModule(true);

  builder.setDefaultLandscape(landscape);

  builder.setFrontCameraMirror(isFrontCameraMirror);
  builder.setManualFocus(focus_manual);

  builder.setIsSlightBeauty(false);

  mStreamer = new KSYStreamer(this);
  mStreamer.setConfig(builder.build());
  mStreamer.setDisplayPreview(mCameraPreview);
  mStreamer.setOnStatusListener(mOnErrorListener);
  mStreamer.setBeautyFilter(RecorderConstants.FILTER_BEAUTY_DENOISE);
```

这个是我的所有参赛配置。
mStreamer.updateUrl(content);是在网络请求后会。可以连接上。但是不是很稳定。经常断。连上了还会断线。请问下是哪里的问题。是因为金山云要收费吗？？

**Comment by z2045217** [comment]
我找到问题了。软编出现的。推流不稳定。我还想问下。延迟这个大概多少。

**Comment by chriszeng87** [comment]
延迟和源站、CDN还有播放器的策略都有关系。使用我们的整套服务，可以控制在3s以内

**Comment by WangShang1** [comment]
网络状态不稳定容易崩溃 请问如何解决

**Comment by chriszeng87** [comment]
请提供一下日志？还有复现的机型，系统版本号，使用SDK的版本号(KSYSreamer.getVersion())
