### ISSUE TITLE
delete all recording files from sd card when disk full

### ISSUE THREAD

**Issue by quickstreamingmedia** [ksvc/KSYStreamer_Android#230]
we have coded to record  video as segments. now we need SDK to notify the disk full function and make it delete.

**Comment by begeekmyfriend** [comment]
Hey, I have the same question. What about providing an callback register for notification of disk full and in the callback we can do the deletion.

**Comment by quickstreamingmedia** [comment]
@jinleileiking @tian9246 @fpzeng @pengbins  hello all we are seriously trusted your sdk and waiting for reply. i expect some replying maintainers. i have 4-5 issues i have solved many except 2 am expecting some reply or support from maintainers.

**Comment by buliaoyin** [comment]
Thanks for your concern. Our SDK is mainly focused on mutimedia solution, check disk storage, delete outdated files are common Android operations, which could be done by application developers.

For example you can check the disk storage when got record failed error, and delete outdated files then try again.
