### ISSUE TITLE
so库 crash 掉了

### ISSUE THREAD

**Issue by androidget** [ksvc/KSYStreamer_Android#235]
08-25 16:32:13.875 19707-19707/? A/DEBUG:     #13 pc 000d21d1  /data/app/com.chumslive.android-1/lib/arm/libksylive.so 

08-25 16:32:13.875 19707-19707/? A/DEBUG:     #14 pc 000d375f  /data/app/com.chumslive.android-1/lib/arm/libksylive.so 

 (_ZN9RTCNotify10onRTCEventEiiPc+274)
08-25 16:32:13.875 19707-19707/? A/DEBUG:     #15 pc 000d49a7  /data/app/com.chumslive.android-1/lib/arm/libksylive.so 

 (_ZN7RTCSink10onRegistarE15rtc_status_code+30)
08-25 16:32:13.875 19707-19707/? A/DEBUG:     #16 pc 00108099  /data/app/com.chumslive.android-1/lib/arm/libksylive.so 

 (_ZN13RTCEngineBase14onRegisteStateE15rtc_status_codei+128)
08-25 16:32:13.875 19707-19707/? A/DEBUG:     #17 pc 001080f7  /data/app/com.chumslive.android-1/lib/arm/libksylive.so 

 (_ZThn4_N13RTCEngineBase14onRegisteStateE15rtc_status_codei+6)
08-25 16:32:13.875 19707-19707/? A/DEBUG:     #18 pc 00113a6f  /data/app/com.chumslive.android-1/lib/arm/libksylive.so 

 (_ZN12RTCUserAgent14onRegcCallbackEP18pjsip_regc_cbparam+154)
08-25 16:32:13.875 19707-19707/? A/DEBUG:     #19 pc 00153b2c  /data/app/com.chumslive.android-1/lib/arm/libksylive.so 

08-25 16:32:17.303 1549-2039/? E/InputDispatcher: channel 'bc312cd com.chumslive.android/com.chumslive.android.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

**Comment by androidget** [comment]
crash

**Comment by zanxiaofei** [comment]
是用的什么版本的？从log看你是用了连麦？

**Comment by androidget** [comment]
是的，就是连麦注册后，回调没有回来，反注册，便会CRASH掉

**Comment by chriszeng87** [comment]
金山云自研连麦暂时没有更新计划了，请切换到声网结合版本，谢谢：
https://github.com/ksvcmc/KMCAgoraVRTC_Android
