### ISSUE TITLE
进入时偶现的crash

### ISSUE THREAD

**Issue by androidget** [ksvc/KSYStreamer_Android#236]
08-25 18:49:01.817 29059-29059/? A/DEBUG: pid: 25931, tid: 29024, name: Thread-274  >>> com.chumslive.android <<<
08-25 18:49:01.858 29059-29059/? A/DEBUG:     #16 pc 000d21d1  /data/app/com.chumslive.android-2/lib/arm/libksylive.so
08-25 18:49:01.858 29059-29059/? A/DEBUG:     #17 pc 000d375f  /data/app/com.chumslive.android-2/lib/arm/libksylive.so (_ZN9RTCNotify10onRTCEventEiiPc+274)
08-25 18:49:01.858 29059-29059/? A/DEBUG:     #18 pc 000d49a7  /data/app/com.chumslive.android-2/lib/arm/libksylive.so (_ZN7RTCSink10onRegistarE15rtc_status_code+30)
08-25 18:49:01.858 29059-29059/? A/DEBUG:     #19 pc 00108099  /data/app/com.chumslive.android-2/lib/arm/libksylive.so (_ZN13RTCEngineBase14onRegisteStateE15rtc_status_codei+128)
08-25 18:49:01.858 29059-29059/? A/DEBUG:     #20 pc 001080f7  /data/app/com.chumslive.android-2/lib/arm/libksylive.so (_ZThn4_N13RTCEngineBase14onRegisteStateE15rtc_status_codei+6)
08-25 18:49:01.859 29059-29059/? A/DEBUG:     #21 pc 00113a6f  /data/app/com.chumslive.android-2/lib/arm/libksylive.so (_ZN12RTCUserAgent14onRegcCallbackEP18pjsip_regc_cbparam+154)
08-25 18:49:01.859 29059-29059/? A/DEBUG:     #22 pc 00153b2c  /data/app/com.chumslive.android-2/lib/arm/libksylive.so

**Comment by zanxiaofei** [comment]
是用的连麦库？

**Comment by androidget** [comment]
是的，可以给个在线联系方式吗？

**Comment by androidget** [comment]
这样回复太慢了

**Comment by chriszeng87** [comment]
QQ群： 574179720   你们是我们的连麦的签约客户吗？

**Comment by chriszeng87** [comment]
金山云自研连麦暂时没有更新计划了，请切换到声网结合版本，谢谢：
https://github.com/ksvcmc/KMCAgoraVRTC_Android
