### ISSUE TITLE
Android录屏直播如何实现背景图推流

### ISSUE THREAD

**Issue by weixiaozi** [ksvc/KSYStreamer_Android#237]

**Comment by weixiaozi** [comment]
已经参照摄像头直播的方式执行startImageCapture方法，但会出现背景图与真实的画面闪屏的问题

**Comment by buliaoyin** [comment]
背景图推流时需要停掉录屏采集，或者断掉录屏采集模块跟后续模块的连接

**Comment by weixiaozi** [comment]
停掉与恢复录屏采集的方法是什么

**Comment by buliaoyin** [comment]
如果是在KSYScreenStreamer里面改的话，调用mScreenCapture.stop()就可以了

**Comment by weixiaozi** [comment]
每次调用mScreenCapture.start()的话，就会回到应用弹出权限弹窗，不希望这样，有没有方法解决

**Comment by buliaoyin** [comment]
那就用第二种方法，断掉录屏采集模块跟后续模块的连接.  

断开：  
mScreenCapture.mImgTexSrcPin.disconnect(mImgTexScaleFilter.getSinkPin(), false);

重新连接：  
mScreenCapture.mImgTexSrcPin.connect(mImgTexScaleFilter.getSinkPin());
