### ISSUE TITLE
推流地址url不能重新设置问题

### ISSUE THREAD

**Issue by Goach** [ksvc/KSYStreamer_Android#24]
推流地址一定要进入页面就设置吗？不能进入当前直播页面打开摄像头进入预览状态，然后通过服务后台申请后得到推流地址再设置！如果再开一个预览界面，然后打开直播界面，这样两次打开的操作（第一次已经destroy了），还是会出现刚进入直播页面打开摄像头失败的问题，然后切换下摄像头又好了。

**Comment by Goach** [comment]
推流地址一定要进入页面就设置吗？不能进入当前直播页面打开摄像头进入预览状态，然后通过服务后台申请后得到推流地址再设置！如果再开一个预览界面，然后打开直播界面，这样两次打开的操作（第一次已经destroy了），还是会出现刚进入直播页面打开摄像头失败的问题，然后切换下摄像头又好了。

**Comment by chriszeng87** [comment]
可以重新设置的， 用KSYStreamer.updateUrl(newUrl);

**Comment by zanxiaofei** [comment]
当前不支持，正在进行重构
