### ISSUE TITLE
推流后生成的视频出现音频数据丢失问题

### ISSUE THREAD

**Issue by xiangyutian** [ksvc/KSYStreamer_Android#244]
SDK名称 | KSYLive_android
SDK版本 | v4.3.3.2
设备型号 | 华为荣耀畅玩5X(KIW-TL00H) 
OS版本 | Android 6.0.1
问题描述 | 直播后生成的回放mp4文件中，第28分钟后到第56分钟时间内的音频数据丢失问题，然后56分钟后音频数据恢复至视频结束;
操作描述 | 下载源视频后，分析mp4文件得知，问题时间段内的音频时间戳pts在问题时间点28分钟时错乱引起；
<img width="308" alt="pts" src="https://user-images.githubusercontent.com/1229669/30469042-1a1a2638-9a21-11e7-9991-1d1391e4624e.png">

额外附件 | 视频源地址: http://cncv.mixiong.tv/live-3-release-141300-1-1338548--20170909141844.mp4

**Comment by chriszeng87** [comment]
谢谢反馈，我们先复现下，也请试试推到我们的源站，用我们的CDN能不能复现，谢谢

**Comment by chriszeng87** [comment]
已确认，是第三方CDN的bug，和SDK本身无关
