### ISSUE TITLE
中间主播切换页面或者离开页面再重连reload或者重新渲染Camera的方式重连会经常出现直播页面卡住，声音能播放。

### ISSUE THREAD

**Issue by Goach** [ksvc/KSYStreamer_Android#26]
中间主播切换页面或者离开页面再回来当前页面观众端重连reload或者重新渲染Camera的方式重连会经常出现直播页面卡住，声音能播放。

**Comment by zanxiaofei** [comment]
机型？软编？硬编？

**Comment by chriszeng87** [comment]
前后台切换请参考 https://github.com/ksvc/KSYStreamer_Android/wiki/Front_Back_Switch
