### ISSUE TITLE
关于64位手机的问题

### ISSUE THREAD

**Issue by advance1989** [ksvc/KSYStreamer_Android#3]
我们是把播放  跟 推流集成在一起了  android端  播放有个文件夹arm64-v8a 里面放了64位机器用到的so文件。 但是推流端没有这个文件夹。导致的问题是 64位机器上推流的时候找这个文件夹的so文件 ，找不到推流的用到的so文件 所以就报错了。 请问该如何解决

**Comment by chriszeng87** [comment]
试试这个：
 armv7a的so库可在arm64的机器上运行，如果APP对arm64-v8a没有强烈需求，可将APP工程libs或jniLibs目录下的arm64-v8a文件夹删除
我们将来会提供arm64-v8a的so库

**Comment by advance1989** [comment]
希望尽快提供，如果删掉文件夹 就会存在其他第三方软件64位的都无法使用

**Comment by chriszeng87** [comment]
最新版本已提供64位版本
