### ISSUE TITLE
拉近拉远时闪退

### ISSUE THREAD

**Issue by WangShang1** [ksvc/KSYStreamer_Android#30]
```
mCamera = mStreamer.getCameraProxy().j();
```

Camera.Parameters params = mCamera.getParameters();
                            params.setZoom(mZoomLeve);
                            mCamera.setParameters(params);
在切换成后置摄像头后变焦闪退，请问如何解决

**Comment by chriszeng87** [comment]
暂时不打算暴露Camera类，请不要这样使用
