### ISSUE TITLE
jnilibs缺少armeabi和x86_64

### ISSUE THREAD

**Issue by pzhangleo** [ksvc/KSYStreamer_Android#32]
作为一个lib库，请提供尽量完整的so库配置，由用户来选择是否使用，多谢，我们现在需要标题上面的两种so，能否尽快在lib中提供？

**Comment by chriszeng87** [comment]
暂时不打算提供，谢谢

**Comment by pzhangleo** [comment]
我们产品面向海外用户，会有这两个平台的需求，请问你们有提供的安排么？或者必须联系你们bd？ @chriszeng87

**Comment by chriszeng87** [comment]
请联系我们的bd吧

**Comment by pzhangleo** [comment]
hi,你们的播放库已经提供了全体系结构的so，你们是否也考虑一下

**Comment by chriszeng87** [comment]
最新版已经提供，谢谢
