### ISSUE TITLE
我用的最新的demo和jar包、so库，结果还是出现UnsatisfiedLinkError

### ISSUE THREAD

**Issue by SunnyBoolean** [ksvc/KSYStreamer_Android#34]
请问是什么原因呢：
 No implementation found for java.util.List com.ksy.recordlib.service.hardware.ksyfilter.KSYCredtpWrapper.getContentList() (tried Java_com_ksy_recordlib_service_hardware_ksyfilter_KSYCredtpWrapper_getContentList and Java_com_ksy_recordlib_service_hardware_ksyfilter_KSYCredtpWrapper_getContentList__)
08-15 14:07:13.580 1808-1808/com.geo.ksmdemo E/AndroidRuntime: FATAL EXCEPTION: main
08-15 14:07:13.580 1808-1808/com.geo.ksmdemo E/AndroidRuntime: Process: com.geo.ksmdemo, PID: 1808
08-15 14:07:13.580 1808-1808/com.geo.ksmdemo E/AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for java.util.List com.ksy.recordlib.service.hardware.ksyfilter.KSYCredtpWrapper.getContentList() (tried Java_com_ksy_recordlib_service_hardware_ksyfilter_KSYCredtpWrapper_getContentList and Java_com_ksy_recordlib_service_hardware_ksyfilter_KSYCredtpWrapper_getContentList__)
08-15 14:07:13.580 1808-1808/com.geo.ksmdemo E/AndroidRuntime:     at com.ksy.recordlib.service.hardware.ksyfilter.KSYCredtpWrapper.getContentList(Native Method)
08-15 14:07:13.580 1808-1808/com.geo.ksmdemo E/AndroidRuntime:     at com.ksy.recordlib.service.hardware.ksyfilter.KSYCredtpWrapper.<init>(Unknown Source)
08-15 14:07:13.580 1808-1808/com.geo.ksmdemo E/AndroidRuntime:     at com.ksy.recordlib.service.hardware.ksyfilter.KSYCredtpWrapper.a(Unknown Source)
08-15 14:07:13.580 1808-1808/com.geo.ksmdemo E/AndroidRuntime:     at com.ksy.recordlib.service.hardware.ksyfilter.KSYImageFilter.<init>(Unknown Source)
08-15 14:07:13.580 1808-1808/com.geo.ksmdemo E/AndroidRuntime:     at com.ksy.recordlib.service.hardware.ksyfilter.b.<init>(Unknown Source)
08-15 14:07:13.580 1808-1808/com.geo.ksmdemo E/AndroidRuntime:     at com.ksy.recordlib.service.hardware.ksyfilter.r.a(Unknown Source)
08-15 14:07:13.580 1808-1808/com.geo.ksmdemo E/AndroidRuntime:     at com.ksy.recordlib.service.core.h.setBeautyFilter(Unknown Source)
08-15 14:07:13.580 1808-1808/com.geo.ksmdemo E/AndroidRuntime:     at com.ksy.recordlib.service.core.KSYStreamer.setBeautyFilter(Unknown Source)

**Comment by chriszeng87** [comment]
是3.3.0.8么

**Comment by SunnyBoolean** [comment]
是3.3.0.8

**Comment by SunnyBoolean** [comment]
@chriszeng87 是3.3.0.8。
这是你们的更新日志：
2016-08-08 3.3.0.8
112. 解决的与播放器的融合版本推流几分钟后断流的问题
113. 修改Demo状态回调示例代码
114. 增加上报信息
115. 解决部分native方法无法找到问题

**Comment by chriszeng87** [comment]
留个联系方式？

**Comment by SunnyBoolean** [comment]
@chriszeng87 我QQ：981411335
