### ISSUE TITLE
分辨率咨询

### ISSUE THREAD

**Issue by androidwzq** [ksvc/KSYStreamer_Android#42]
你好，请问能否设置分辨率

**Comment by chriszeng87** [comment]
暂时不支持自定义分辨率，但您可以选择360P, 480P,540P,720P。大约三四周后的版本可以支持自定义分辨率

**Comment by chriszeng87** [comment]
已支持自定义分辨率 https://github.com/ksvc/KSYStreamer_Android/wiki/Streamer_Config_Params#%E6%8E%A8%E6%B5%81%E5%88%86%E8%BE%A8%E7%8E%87
