### ISSUE TITLE
魅族Pro5推流手机浏览黑屏，但是流有画面

### ISSUE THREAD

**Issue by gzasgjq** [ksvc/KSYStreamer_Android#43]
Android版本：5.1 没有root 固件版本Flyme5.6.8.23 beta

log信息警告：
08-25 18:11:38.971 12656-13021/com.ksyun.live.demo W/KSYMediaPlayer: AVFrame.width or height is not set
08-25 18:11:39.031 12656-13021/com.ksyun.live.demo W/KSYMediaPlayer: AVFrame.format is not set

**Comment by buliaoyin** [comment]
该机型Flyme5.1.8.0A正式版固件上未复现该问题，可能是手机beta版固件的bug.

**Comment by gzasgjq** [comment]
目前换到5.1.9.0A版本固件之后仍然黑屏，但是没有Log Warn了

**Comment by buliaoyin** [comment]
该机型5.1.9.0A固件上确实存在该问题，已定位，下个版本修复。
另外，前述的log warn信息可以忽略。
