### ISSUE TITLE
美图效果不是很好啊，最重要的是很卡顿啊。

### ISSUE THREAD

**Issue by z2045217** [ksvc/KSYStreamer_Android#47]
一般的手机卡的一阵一阵的。只有在顶配机上面还好些。

**Comment by zanxiaofei** [comment]
美颜？软编？

**Comment by overflyforever** [comment]
请问下您使用的手机型号具体是哪些呢？一般的旗舰级都不会卡顿的

**Comment by z2045217** [comment]
恩。硬编。红米note ，还有美图手机。都会很卡顿。我在三星note s7上面试了。不卡顿。但是这个要求太高了吧。

**Comment by overflyforever** [comment]
应该是机型以及硬件的问题 硬编的话还是需要主流一些的机型才会比较流畅的

**Comment by buliaoyin** [comment]
目前Denoise算法可以流畅运行在各种机型上，其他美颜算法的效果及效率问题，我们一直在做优化，还请保持关注。

**Comment by buliaoyin** [comment]
v4.0.0beta已发布，该版本大幅提高了美颜性能，目前在主流机型上均可流畅运行，还请关注下。

**Comment by z2045217** [comment]
正在看。一直都很关注金山家的直播。

**Comment by z2045217** [comment]
我调式好了。才发现。人物有点动作会有花屏的现象。马赛克挺严重的。

**Comment by buliaoyin** [comment]
关于花屏和马赛克，还请提供更详细的描述，是使用软编、硬编还是软编兼容模式，码率设置是多少？是用什么机型测试的？网络状况如何？

另外，4.0.0正式版本即将发布，届时您也可以用正式版本再进行验证。

**Comment by buliaoyin** [comment]
v4.0.0正式版已发布，还请再验证下。
马赛克严重一般是码率设置过低引起的，4.0的mStreamer.setVideoBitrate(int)中的参数单位是bps，而不是kbps，这点还请先确认下。
