### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by rcwind** [ksvc/KSYStreamer_Android#50]
java.lang.UnsatisfiedLinkError
No implementation found for java.util.List com.ksy.recordlib.service.hardware.ksyfilter.KSYCredtpWrapper.getContentList() (tried Java_com_ksy_recordlib_service_hardware_ksyfilter_KSYCredtpWrapper_getContentList and Java_com_ksy_recordlib_service_hardware_ksyfilter_KSYCredtpWrapper_getContentList__)

com.ksy.recordlib.service.hardware.ksyfilter.KSYCredtpWrapper.java.util.List getContentList()(Native Method) 

com.ksy.recordlib.service.hardware.ksyfilter.KSYCredtpWrapper.void <init>()(Unknown Source) 

com.ksy.recordlib.service.hardware.ksyfilter.KSYCredtpWrapper.com.ksy.recordlib.service.hardware.ksyfilter.KSYCredtpWrapper a()(Unknown Source)

**Comment by fpzeng** [comment]
Version information?

**Comment by Goach** [comment]
同样遇到这个问题，升级到android studio 2.2.0，然后就出现这个问题了

**Comment by dhcn** [comment]
我猜一下，估计是把Java8的编译状态给开了。

**Comment by Goach** [comment]
我现在也还在调试，没升级前是好的，代码什么都没改，升级后，就这样了，怎么关闭java8的编译状态

**Comment by Goach** [comment]
我用的是jdk1.8.0_74

**Comment by dhcn** [comment]
/*compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }*/

**Comment by Goach** [comment]
没有开启，我的是这样的
compileOptions {
            sourceCompatibility JavaVersion.VERSION_1_7
            targetCompatibility JavaVersion.VERSION_1_7
        }

**Comment by Goach** [comment]
那3.3.0.5版本是不能开启Java8的编译环境是吧？？？

**Comment by chriszeng87** [comment]
更新一下最新的版本试试吧，这个问题我们应该已经修复了

**Comment by zanxiaofei** [comment]
你是在3.3.0.5 上发生问题的？我们3.3.0.8把这个问题修复了。麻烦确认一下版本信息

**Comment by zanxiaofei** [comment]
我的就是AndroidStudio 2.2 应该跟这个没有关系的
