### ISSUE TITLE
推流和拉流的URL是怎么获取的？

### ISSUE THREAD

**Issue by okadaNana** [ksvc/KSYStreamer_Android#53]
看了[金山云直播服务说明](http://www.ksyun.com/doc/art/id/525)，这篇文章没看明白

**Comment by chriszeng87** [comment]
可以联系我们的商务，申请开通直播服务，我们会给您提供推流和拉流URL

**Comment by owenmike** [comment]
没有提供一个接口吗？
主播直播的时候，应用服务器请求金山云的接口返回一个推流URL和拉流URL。主播的手机向推流URL推流，观众从拉流URL中拉流

**Comment by chriszeng87** [comment]
向所有的客户都提供统一的接口，这样区分不了不同的客户哈。让您申请开通直接服务，也是为了您考虑。能留个联系方式么，我找我们的商务来联系您。
