### ISSUE TITLE
推流时很频繁遇到的错误：KSYVIDEO_CONNECT_BREAK

### ISSUE THREAD

**Issue by RadiateWSG** [ksvc/KSYStreamer_Android#56]
09-23 15:27:40.590 18540-30676/com.**_.debug E/KSYMediaPlayer: Application provided invalid, non monotonically increasing dts to muxer in stream 1: 427534 >= 426854
09-23 15:27:40.590 18540-30676/com.**_.debug E/streamer: ------av_interleaved_write_frame() error:-22 while writing interleaved audio frame
09-23 15:27:40.590 18540-30676/com.**_.debug W/StreamLogReportManger: on status changed :-1007
09-23 15:27:40.017 18540-30676/com.**_.debug I/System.out: 460007832152498
09-23 15:27:40.018 18540-30676/com.**_.debug I/StreamLogReportManger: stopStream :true
09-23 15:27:40.018 18540-30676/com.**_.debug E/LiveStreamActivity: [audio_encode_thread]the streaming stopped because KSYVIDEO_CONNECT_BREAK

以上是最近测试中经常碰到的错误，推流时网络正常，是我使用API的问题呢？还是sdk的bug呢？其他开发者有碰到这个问题吗？

**Comment by RadiateWSG** [comment]
另，推流时一直输出这个警告：
W/KSYMediaPlayer: AVFrame.format is not set
W/KSYMediaPlayer: AVFrame.width or height is not set

**Comment by chriszeng87** [comment]
警告可以忽略，KSYVIDEO_CONNECT_BREAK这个应该是网络不好，麻烦您用我们的Demo复现下？
