### ISSUE TITLE
CameraGLSurfaceView设置的固定宽高不管用   不管怎么设置都是全屏显示？ 

### ISSUE THREAD

**Issue by zhuminquan** [ksvc/KSYStreamer_Android#58]
CameraGLSurfaceView设置的固定宽高不管用   不管怎么设置都是全屏显示

**Comment by chriszeng87** [comment]
暂时只支持全屏，在接下来的两个版本后可以支持自定义

**Comment by chriszeng87** [comment]
已支持自定义： https://github.com/ksvc/KSYStreamer_Android/wiki/Streamer_Config_Params#%E9%A2%84%E8%A7%88%E5%88%86%E8%BE%A8%E7%8E%87
