### ISSUE TITLE
Error:Connection refused

### ISSUE THREAD

**Issue by qylshy** [ksvc/KSYStreamer_Android#59]
demo 运行不了提示Error:Connection refused
![image](https://cloud.githubusercontent.com/assets/5379447/18873357/9ba7324a-84f1-11e6-9c32-53854fd5d041.png)

**Comment by chriszeng87** [comment]
Android Studio的问题，你clean一下再运行吧

**Comment by zhuminquan** [comment]
在build.gradle中修改如下试试
dependencies {
        classpath 'com.android.tools.build:gradle:2.1.0'
    }
