### ISSUE TITLE
关于64位机子的问题

### ISSUE THREAD

**Issue by advance1989** [ksvc/KSYStreamer_Android#6]
请提供64位机子的so文件。因为app中集成了其他第三方的64位库。导致我们在arm64文件夹中没有so文件，程序崩溃！

**Comment by chriszeng87** [comment]
Coming soon. Maybe next week.

**Comment by advance1989** [comment]
help me   please quickly！！

**Comment by chriszeng87** [comment]
最新版本已提供64位版本
