### ISSUE TITLE
推流时候可以同时使用mideaRecord进行本地录制吗？

### ISSUE THREAD

**Issue by gangmiangongjue** [ksvc/KSYStreamer_Android#63]
mideaRecord进行录制需要拿到camera对象，但是camera对象已经被完全封装进去了，或者API中已经有了录制的接口？

**Comment by chriszeng87** [comment]
你是要实现边录边推的功能?

**Comment by gangmiangongjue** [comment]
是的

**Comment by gordonpro** [comment]
我测试过可以。通过
`mStreamer.setOnPreviewFrameListener`

会把 byte[] 回调到这里，然后我在这里用 MediaCodec 和 MediaMuxer 把数据存成了 mp4.

但是感觉有问题，因为水印和美化都没了。而且视频不能定位，每次定位都自动重新播放。

**Comment by gordonpro** [comment]
如果有自带的实现就好了

**Comment by chriszeng87** [comment]
没有必要本地录制，使用我们的服务，推的同时，会在服务端保存一份视频文件，如果需要，直接播这个文件就可以了。如果时间长了，这个文件太大了。您可以和产品好好沟通下。

**Comment by gangmiangongjue** [comment]
好的，然而我觉得最简单的方式还是贵平台把封装进去的camera对象，暴露一个get方法，这样直接使用安卓提供最简单的方式就可以保存了。都存在服务端上这个量大的话，处理确实是个问题

**Comment by gangmiangongjue** [comment]
@gordonpro 你觉得是不是把camera直接曝露出来，使用mediarecorder最为简单呢？

**Comment by gordonpro** [comment]
@gangmiangongjue Camera你要拿到 直接就可以. mStreamer 里面有个变量就是。 但是你拿到Camera对象是没用的，因为在录制的过程中，Camera是被占用的，你无法操作。更加不可能用MediaRecorder了。 
顶多只能获取 preview 的二进制内容, 每一帧 YUV 用 MediaCodec 保存成 mp4。

如果 `mStreamer ` 能暴露一个方法，把水印和美化后的最终preview数据 回调就能做本地保存了。

**Comment by gordonpro** [comment]
还有一种牛逼的方法是直接 Surface 转成 流。 性能更好。

**Comment by buliaoyin** [comment]
当前我们没有支持边推边存储到本地的计划。
如果一定要实现，v4.0下可以参考如下思路：

首先，通过mStreamer.getVideoEncoderMgt().getEncoder()与mStreamer.getAudioEncoderMgt().getEncoder()分别拿到视频跟音频的Encoder;
然后分别继承 `SinkPin<ImgBufFrame>` 跟 `SinkPin<AudioBufFrame>` 实现两个数据消耗类；
分别用前面获取的Encoder.mSrcPin.connect([your sink])，然后就能在你实现的Sink类中的onFrameAvailable函数中拿到跟推流一致的编码后的数据了。
接下来就是把编码后的数据mux并存储了。

具体参考4.0的javadoc：
http://ksvc.github.io/KSYStreamer_Android/docs/reference/packages.html

**Comment by gangmiangongjue** [comment]
好的，有空研究下，谢谢开发者的无私帮助

**Comment by CodeDreamInTheWay** [comment]
@gangmiangongjue 边推边录你有眉目了吗？我最近一直在搞这个，ffmpeg，openvc都用上了，ffmpeg命令录制流效果差，openvc丢帧严重，请问你用的什么办法，一起讨论下，方便的话加个QQ442827954

**Comment by CodeDreamInTheWay** [comment]
@gangmiangongjue 4.0的参考思路有吗？

**Comment by CodeDreamInTheWay** [comment]
@gordonpro 请问你边推边录的方案解决了吗？请问你用的什么办法，一起讨论下，方便的话加个QQ442827954，谢谢

**Comment by CodeDreamInTheWay** [comment]
@buliaoyin 如何继承 SinkPin<ImgBufFrame> 跟 SinkPin<AudioBufFrame>这两个类

**Comment by chriszeng87** [comment]
连推边录已上线 https://github.com/ksvc/KSYStreamer_Android/wiki/file_pub
