### ISSUE TITLE
How to make FILTER_BEAUTY_ILLUSION smoother

### ISSUE THREAD

**Issue by ngochuu90** [ksvc/KSYStreamer_Android#64]
Hello 

This is my config
![device-2016-10-11-140646](https://cloud.githubusercontent.com/assets/9895294/19261527/102b9b36-8fbc-11e6-9d12-300cb54ae944.png)

When I choose FILTER_BEAUTY_ILLUSION, video recorder not as smooth as FILTER_BEAUTY_DENOISE

**Comment by buliaoyin** [comment]
FILTER_BEAUTY_ILLUSION has performance issue on 3.x version, our 4.0 official version will be release by tomorrow, which had got huge performance improvement on every GPU beauty filter.

Today, you can try our v4.0.0beta version for performance evaluation: https://github.com/ksvc/KSYStreamer_Android/releases/tag/v4.0.0beta

**Comment by ngochuu90** [comment]
Thanks for answering !
