### ISSUE TITLE
推流的时候  点击进入其他界面,推流就结束了  怎么解决

### ISSUE THREAD

**Issue by delonglimin** [ksvc/KSYStreamer_Android#67]
推流的时候  点击进入其他界面,推流就结束了  怎么解决

**Comment by gordonpro** [comment]
因为你进入其他页面 相机被关闭了。这个是必然的

**Comment by buliaoyin** [comment]
v4.0支持推流Activity进入后台时，只推音频，切换回来后继续推视频的机制，整个过程推流session不会中断。具体请参考wiki中的说明。

**Comment by delonglimin** [comment]
推流进入其他页面,只是把它压入栈中,并没有销毁,当我返回的时候,相机还是开着的,很显然相机没有关闭,只是停止推流了

**Comment by delonglimin** [comment]
推流进入其他页面,只是把它压入栈中,并没有销毁,当我返回的时候,相机还是开着的,很显然相机没有关闭,只是停止推流了

**Comment by delonglimin** [comment]
推流进入其他页面,只是把它压入栈中,并没有销毁,当我返回的时候,相机还是开着的,很显然相机没有关闭,只是停止推流了

**Comment by delonglimin** [comment]
返回的时候  报的错误   pts diff: 5024

**Comment by gordonpro** [comment]
页面 onPause 相机就没了Preview了，所以streamer 拿不到视频数据。

**Comment by chriszeng87** [comment]
请参考  https://github.com/ksvc/KSYStreamer_Android/wiki/Front_Back_Switch
