### ISSUE TITLE
The watermark will replaced after pressed the home key and returned

### ISSUE THREAD

**Issue by kingbeful** [ksvc/KSYStreamer_Android#74]
I've add a watermark to the camera preview with the code below:

`mStreamer.showWaterMarkLogo("assets://watermark.png", 0.03f, 0.03f, 0.15f, 0.15f, 0.8f);`

But when I press the home key and return the my app again, the watermark will be replaced by the camera preview. And my app's screen will look like in a picture in picture mode.

I'm using the latest 4.0.1

**Comment by buliaoyin** [comment]
Did you hide watermark in onPause and show it again in onResume?

**Comment by kingbeful** [comment]
My fault.

It works fine when I add hide watermark in onPause.

Thank you.

**Comment by chriszeng87** [comment]
Please close the issue if your problem is solved, thanks.
