### ISSUE TITLE
推流还没有返回SUCCESS时关闭页面，会卡顿

### ISSUE THREAD

**Issue by VeamW** [ksvc/KSYStreamer_Android#84]
Android：
Activity A--> CameraActivity   .  在CameraActivity中完成初始化streamer的操作以及推流操作！
情况： 当我进入到CameraActivity中，又立刻关闭CameraActivity时，会返回到A ，但是A 的所有控件都无法获得焦点（被阻塞），过几秒钟之后，streamer会返回一个Failed connect to  "url"  的错误（这个应该是streamer释放的问题）。

情况：当我在直播过成功，去到另一个页面（此activity并没有被finish），然后推流就断开了，再次进入会重新推流！！！！！！  设置了setAudio没有用！！！！！

**Comment by buliaoyin** [comment]
关于前面的block问题，我们这边验证，在网络状况非常糟糕的情况下会有一定概率出现，block在一个系统调用上面。这个问题我们后续会fix掉。
后面一个问题还请先参照demo自行排查。

**Comment by chriszeng87** [comment]
已修复，请用最新版本试试
