### ISSUE TITLE
这个统计发送功能怎么取消掉？

### ISSUE THREAD

**Issue by dhcn** [ksvc/KSYStreamer_Android#85]
D/StreamSucessCount: JSON content:{"sdk_type":"streamer","sdk_ver":"4.0.1.0","sdk_ver_sub":"4.0.1.0","platform":"android","os_ver":"5.1.1","pkg":"UNKNOWN","dev_model":"Mi-4c","dev_id":"UNKNOWN","log_ver":"1.0.2","log_vn":101}
11-11 12:12:08.548 5841-8846/com.xiangbita.dqk.dqkand I/StreamSucessCount: begin to send success count: http://videodev.ksyun.com:8980

**Comment by chriszeng87** [comment]
不建议去掉

**Comment by dhcn** [comment]
我用的是自建的直播服务器啊。

**Comment by chriszeng87** [comment]
也不建议去掉

**Comment by hike2008** [comment]
不建议去掉... 那能去掉吗... 统计的目的是什么

**Comment by dhcn** [comment]
推流的URL里面有鉴权隐私数据，你这统计着，容易形成后门。
