### ISSUE TITLE
无网络丢包下帧率会小于预设帧率？

### ISSUE THREAD

**Issue by lonelymemo** [ksvc/KSYStreamer_Android#90]
我在使用sdk时，发现网络无丢包的情况下，帧率会小于预设帧率，请问是什么策略导致出现这种情况的？

**Comment by chriszeng87** [comment]
因为这是直播，为了实时性，在网络确实不好的时候丢帧，所有的直播服务都会使用这种策略

**Comment by lonelymemo** [comment]
soga，网络不好这个明白，只是不知道android的设备也会变动。这个是软编造成的么？

**Comment by chriszeng87** [comment]
和软编硬编没关系，摄像头采集到的就是不稳定的

**Comment by lonelymemo** [comment]
摄像头不稳定？那这个是android系统的问题咯。

**Comment by chriszeng87** [comment]
是的, iOS的就不会有这个问题
