### ISSUE TITLE
推流到facebook

### ISSUE THREAD

**Issue by ChinaLinda** [ksvc/KSYStreamer_Android#94]
如果推流到facebook
调用stopStream() 会导致facebook的推流地址失效
再次startStram() 时无法推流成功
是否有可以实现短时间暂停推流而不是完全停止推流的方法

推流到国内平台不会出现此问题 国内的逻辑是stop即pause

**Comment by buliaoyin** [comment]
目前我们的KSYStreamer没有提供类似的接口，不过当前我们的SDK已经实现了组件化，KSYStreamer的实现代码也已经公开，你可以参考其实现进行定制化。
https://github.com/ksvc/KSYStreamer_Android/blob/master/src/KSYStreamer.java
